# Sistema Agentivo para Análise Exploratória e Controle de Qualidade de Dados de Monitoramento da Qualidade da Água

## 1. Contexto do projeto

O objetivo deste projeto é construir um sistema de trabalho capaz de conduzir, de forma consistente, verificável e reutilizável, uma análise exploratória e um processo de controle de qualidade de dados de monitoramento da qualidade das águas.

A proposta não é substituir a análise técnica por uma resposta de modelo de linguagem. O sistema combina operações determinísticas realizadas por código com uma camada de interpretação, permitindo maior rastreabilidade, validação dos resultados e controle sobre as conclusões produzidas.

---

## 2. Domínio e escopo

**Domínio:** monitoramento da qualidade das águas superficiais em Minas Gerais.

**Usuário-alvo:** analista ambiental ou profissional responsável pela análise de dados de monitoramento.

**Pergunta orientadora:**

> Quais problemas de qualidade e completude dos dados, padrões temporais e observações que merecem investigação podem ser identificados automaticamente a partir de uma série histórica de monitoramento?

**Decisão apoiada:**

Identificar períodos, parâmetros e observações que devem receber atenção ou investigação adicional antes da utilização dos dados em análises ambientais.

O sistema está deliberadamente restrito a esse domínio e família de dados. Ele não pretende produzir diagnóstico ambiental definitivo ou substituir a avaliação de especialistas.

---

## 3. Dados utilizados

Foi utilizada a base histórica de dados de qualidade das águas do Programa Águas de Minas, do Instituto Mineiro de Gestão das Águas (IGAM).

O arquivo utilizado nesta demonstração é:

**Dados_Qualidade_das_Aguas_ate_2019.xlsx**

A análise utiliza principalmente a planilha **"SH ATÉ DEZ 2019"**.

Características observadas na base:

- 39.615 registros de amostragem;
- 769 estações;
- 96 parâmetros ambientais;
- período de 1997 a 2019;
- estrutura com colunas de valor e respectivas colunas de sinal;
- dados físico-químicos e microbiológicos;
- presença de valores ausentes em diferentes níveis de cobertura.

A base completa é preservada e os dados ausentes não são removidos automaticamente.

---

## 4. Recorte analítico

Embora a base contenha 96 parâmetros, a auditoria exploratória utiliza um conjunto reduzido de 11 parâmetros principais:

- pH in loco;
- Turbidez;
- Oxigênio dissolvido;
- Temperatura da água;
- Condutividade elétrica in loco;
- Demanda Bioquímica de Oxigênio;
- Fósforo total;
- Nitrato;
- Sólidos totais;
- Nitrogênio amoniacal total;
- Coliformes termotolerantes.

A seleção considera relevância para a caracterização da qualidade da água, cobertura na série histórica, diversidade de dimensões ambientais e viabilidade de demonstração do sistema.

Os demais parâmetros permanecem preservados na base e podem ser incorporados a análises futuras conforme a pergunta analítica e a disponibilidade dos dados.

---

## 5. Estratégia do sistema

O fluxo desenvolvido neste projeto é:

**Entrada dos dados**
→ **Auditoria e controle de qualidade**
→ **Padronização**
→ **Análise exploratória**
→ **Validação dos achados**
→ **Relatório**

As operações críticas, como contagem, cálculo de cobertura, identificação de duplicidades e estatísticas, são realizadas por código determinístico.

A camada de linguagem pode ser utilizada para interpretar os resultados e comunicar os achados, mas não substitui as verificações executadas pelo sistema.

---

## 6. Princípios de confiabilidade

O sistema foi desenvolvido com alguns princípios:

- preservar os dados originais;
- preservar valores ausentes;
- preservar os sinais associados às medições;
- não classificar automaticamente valores extremos como erros;
- diferenciar evidência de interpretação;
- não inferir causalidade a partir de associações ou lacunas;
- registrar as verificações realizadas;
- bloquear ou sinalizar etapas quando os critérios mínimos não forem atendidos.

---

## 7. Limitações e fora do escopo

Este projeto não pretende:

- estabelecer relações de causalidade;
- determinar a causa de dados ausentes;
- produzir diagnóstico ambiental definitivo;
- determinar risco à saúde;
- afirmar conformidade regulatória;
- substituir avaliação técnica especializada;
- realizar previsão futura sem uma pergunta e dados adequados para modelagem preditiva.

Os resultados devem ser interpretados dentro do escopo e das limitações da base analisada.

In [ ]:
# Carregar base de dados
from pathlib import Path
import pandas as pd

caminhos_possiveis = [
    Path("data") / "Dados_Qualidade_das_Aguas_ate_2019.xlsx",
    Path("../data") / "Dados_Qualidade_das_Aguas_ate_2019.xlsx"
]

arquivo = next(
    (caminho for caminho in caminhos_possiveis if caminho.exists()),
    None
)

if arquivo is None:
    raise FileNotFoundError(
        "Base de dados não encontrada. "
        "Verifique se o arquivo está na pasta data/ do projeto."
    )

xls = pd.ExcelFile(arquivo)

print(f"Arquivo utilizado: {arquivo}")
print(xls.sheet_names)

['SH ATÉ DEZ 2019', 'SCQA CIANO E ECOTOX 2018', 'SCQA ECOTOX E CIANO ANUAL 2019', 'SCQA IQA 2018', 'SCQA IQA TRIMESTRAL 2019', 'SCQA CT 2018', 'SCQA CT ANUAL 2019', 'SCQA IET 2018', 'SCQA IET ANUAL 2019']

In [ ]:
# Verificar abas do arquivo
for aba in xls.sheet_names:
    df = pd.read_excel(arquivo, sheet_name=aba)

    print(f"\nABA: {aba}")
    print(f"Linhas: {df.shape[0]}")
    print(f"Colunas: {df.shape[1]}")

ABA: SH ATÉ DEZ 2019
Linhas: 39615
Colunas: 195

ABA: SCQA CIANO E ECOTOX 2018
Linhas: 342
Colunas: 7

ABA: SCQA ECOTOX E CIANO ANUAL 2019
Linhas: 1328
Colunas: 7

ABA: SCQA IQA 2018
Linhas: 630
Colunas: 6

ABA: SCQA IQA TRIMESTRAL 2019
Linhas: 650
Colunas: 6

ABA: SCQA CT 2018
Linhas: 626
Colunas: 6

ABA: SCQA CT ANUAL 2019
Linhas: 649
Colunas: 6

ABA: SCQA IET 2018
Linhas: 630
Colunas: 6

ABA: SCQA IET ANUAL 2019
Linhas: 650
Colunas: 6

In [ ]:
# Verificar estrutura das unidades de observação
df = pd.read_excel(
    arquivo,
    sheet_name="SH ATÉ DEZ 2019"
)

df.head()

,Estação,Data de Amostragem,Hora de Amostragem,"Sinal 2,4,6 Triclorofenol","2,4,6 Triclorofenol",Sinal Alcalinidade de bicarbonato,Alcalinidade de bicarbonato,Sinal Alcalinidade total,Alcalinidade total,Sinal Aldrin + Dieldrin,...,Sinal Transparência,Transparência,Sinal Trifluoralina,Trifluoralina,Sinal Turbidez,Turbidez,Sinal Vanádio total,Vanádio total,Sinal Zinco total,Zinco total
0,AV005,2003-01-13,11:20:00,NaN,NaN,NaN,NaN,NaN,8.1,NaN,...,NaN,NaN,NaN,NaN,NaN,31.90,NaN,NaN,<,0.02
1,AV005,2003-04-01,10:35:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.30,NaN,NaN,NaN,NaN
2,AV005,2003-07-01,10:40:00,NaN,NaN,NaN,NaN,NaN,10.8,NaN,...,NaN,NaN,NaN,NaN,NaN,1.87,NaN,NaN,<,0.02
3,AV005,2003-10-02,11:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.45,NaN,NaN,NaN,NaN
4,AV005,2004-01-12,11:00:00,NaN,NaN,NaN,NaN,NaN,10.6,NaN,...,NaN,NaN,NaN,NaN,NaN,9.14,NaN,NaN,<,0.02

Warning: Total number of columns (195) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df[
    [
        "Estação",
        "Data de Amostragem",
        "Hora de Amostragem"
    ]
].head(10)

  Estação Data de Amostragem Hora de Amostragem
0   AV005         2003-01-13           11:20:00
1   AV005         2003-04-01           10:35:00
2   AV005         2003-07-01           10:40:00
3   AV005         2003-10-02           11:05:00
4   AV005         2004-01-12           11:00:00
5   AV005         2004-04-01           11:10:00
6   AV005         2004-07-05           10:55:00
7   AV005         2004-10-01           10:35:00
8   AV005         2006-10-02           10:50:00
9   AV005         2007-01-22           10:10:00

In [ ]:
# Cobertura temporal dos dados
df["Data de Amostragem"] = pd.to_datetime(
    df["Data de Amostragem"],
    errors="coerce"
)

print(df["Data de Amostragem"].min())
print(df["Data de Amostragem"].max())

1997-07-02 00:00:00
2019-12-12 00:00:00

In [ ]:
# Registros por ano
df["ano"] = df["Data de Amostragem"].dt.year

df["ano"].value_counts().sort_index()

ano
1997     421
1998     745
1999     795
2000     959
2001     962
2002     971
2003    1159
2004    1161
2005    1156
2006    1322
2007    1534
2008    1841
2009    2055
2010    2183
2011    2309
2012    2386
2013    2586
2014    2637
2015    2626
2016    2542
2017    1734
2018    2745
2019    2786
Name: count, dtype: int64

In [ ]:
# Quantidade de estações
df["Estação"].nunique()

769

In [ ]:
df["Estação"].value_counts().head(20)

Estação
BV141    174
BV146    174
BV139    174
BV149    174
BV152    174
BV105    174
BV148    174
BV156    173
BV063    163
BV142    154
BV013    154
BV083    154
BV037    154
BV067    154
BV137    154
BV153    148
RD033    136
RD045    136
RD019    136
RD059    136
Name: count, dtype: int64

In [ ]:
df.groupby("ano")["Estação"].nunique()

ano
1997    195
1998    201
1999    202
2000    242
2001    242
2002    248
2003    278
2004    278
2005    319
2006    372
2007    416
2008    471
2009    489
2010    535
2011    563
2012    587
2013    605
2014    585
2015    591
2016    592
2017    597
2018    626
2019    649
Name: Estação, dtype: int64

In [ ]:
# Verificar parâmetros
colunas = df.columns.tolist()

for coluna in colunas:
    print(coluna)

Estação
Data de Amostragem
Hora de Amostragem
Sinal 2,4,6 Triclorofenol
2,4,6 Triclorofenol
Sinal Alcalinidade de bicarbonato
Alcalinidade de bicarbonato
Sinal Alcalinidade total
Alcalinidade total
Sinal Aldrin + Dieldrin
Aldrin + Dieldrin
Sinal Alumínio dissolvido
Alumínio dissolvido
Sinal Alumínio total
Alumínio total
Sinal Arsênio Dissolvido
Arsênio Dissolvido
Sinal Arsênio total
Arsênio total
Sinal Atrazina
Atrazina
Sinal Bário total
Bário total
Sinal Boro dissolvido
Boro dissolvido
Sinal Boro total
Boro total
Sinal Cádmio total
Cádmio total
Sinal Cálcio total
Cálcio total
Sinal Chumbo total
Chumbo total
Sinal Cianeto Livre
Cianeto Livre
Sinal Cianeto total
Cianeto total
Sinal Clordano - cis + trans
Clordano - cis + trans
Sinal Cloreto total
Cloreto total
Sinal Clorofila a
Clorofila a
Sinal Cobre dissolvido
Cobre dissolvido
Sinal Cobre total
Cobre total
Sinal Coliformes termotolerantes
Coliformes termotolerantes
Sinal Coliformes totais
Coliformes totais
Sinal Condição de tempo
Condição de tempo
Sinal Condutividade elétrica in loco
Condutividade elétrica in loco
Sinal Condutividade elétrica laboratório
Condutividade elétrica laboratório
Sinal Cor verdadeira
Cor verdadeira
Sinal Cromo hexavalente
Cromo hexavalente
Sinal Cromo total
Cromo total
Sinal Cromo trivalente
Cromo trivalente
Sinal DDT
DDT
Sinal Demanda Bioquímica de Oxigênio
Demanda Bioquímica de Oxigênio
Sinal Demanda Química de Oxigênio
Demanda Química de Oxigênio
Sinal Densidade de cianobactérias
Densidade de cianobactérias
Sinal Descarga Liquida
Descarga Liquida
Sinal Dureza de Cálcio
Dureza de Cálcio
Sinal Dureza de magnésio
Dureza de magnésio
Sinal Dureza total
Dureza total
Sinal Endossulfan - alfa + beta
Endossulfan - alfa + beta
Sinal Endrin
Endrin
Sinal Ensaio ecotoxicológico
Ensaio ecotoxicológico
Sinal Escherichia coli
Escherichia coli
Sinal Estanho total
Estanho total
Sinal Estreptococos fecais
Estreptococos fecais
Sinal Fenóis totais
Fenóis totais
Sinal Feoftina a
Feoftina a
Sinal Ferro dissolvido
Ferro dissolvido
Sinal Ferro total
Ferro total
Sinal Fluoreto ionizado
Fluoreto ionizado
Sinal Fósforo total
Fósforo total
Sinal Heptacloro epóxido + Heptacloro
Heptacloro epóxido + Heptacloro
Sinal Hexaclorobenzeno
Hexaclorobenzeno
Sinal Lindano
Lindano
Sinal Magnésio total
Magnésio total
Sinal Manganês dissolvido
Manganês dissolvido
Sinal Manganês total
Manganês total
Sinal Mercúrio total
Mercúrio total
Sinal Metoxicloro
Metoxicloro
Sinal Microcistina
Microcistina
Sinal Molinato
Molinato
Sinal Níquel total
Níquel total
Sinal Nitrato
Nitrato
Sinal Nitrito
Nitrito
Sinal Nitrogênio amoniacal total
Nitrogênio amoniacal total
Sinal Nitrogênio orgânico
Nitrogênio orgânico
Sinal Óleos e graxas
Óleos e graxas
Sinal Ortofosfato
Ortofosfato
Sinal Oxigênio dissolvido
Oxigênio dissolvido
Sinal Pentaclorofenol
Pentaclorofenol
Sinal Permetrina - cis + trans
Permetrina - cis + trans
Sinal pH in loco
pH in loco
Sinal pH laboratório
pH laboratório
Sinal Potássio dissolvido
Potássio dissolvido
Sinal Potássio total
Potássio total
Sinal Precipitação
Precipitação
Sinal Profundidade
Profundidade
Sinal Saxitoxina
Saxitoxina
Sinal Selênio total
Selênio total
Sinal Simazina
Simazina
Sinal Sódio dissolvido
Sódio dissolvido
Sinal Sódio total
Sódio total
Sinal Sólidos dissolvidos totais
Sólidos dissolvidos totais
Sinal Sólidos em suspensão totais
Sólidos em suspensão totais
Sinal Sólidos sedimentáveis
Sólidos sedimentáveis
Sinal Sólidos totais
Sólidos totais
Sinal Substâncias tensoativas
Substâncias tensoativas
Sinal Sulfato total
Sulfato total
Sinal Sulfeto
Sulfeto
Sinal Temperatura da água
Temperatura da água
Sinal Temperatura do ar
Temperatura do ar
Sinal Transparência
Transparência
Sinal Trifluoralina
Trifluoralina
Sinal Turbidez
Turbidez
Sinal Vanádio total
Vanádio total
Sinal Zinco total
Zinco total
ano

In [ ]:
colunas_sinal = [
    c for c in df.columns
    if c.startswith("Sinal")
]

print(colunas_sinal)

['Sinal 2,4,6 Triclorofenol', 'Sinal Alcalinidade de bicarbonato', 'Sinal Alcalinidade total', 'Sinal Aldrin + Dieldrin', 'Sinal Alumínio dissolvido', 'Sinal Alumínio total', 'Sinal Arsênio Dissolvido', 'Sinal Arsênio total', 'Sinal Atrazina', 'Sinal Bário total', 'Sinal Boro dissolvido', 'Sinal Boro total', 'Sinal Cádmio total', 'Sinal Cálcio total', 'Sinal Chumbo total', 'Sinal Cianeto Livre', 'Sinal Cianeto total', 'Sinal Clordano - cis + trans', 'Sinal Cloreto total', 'Sinal Clorofila a', 'Sinal Cobre dissolvido', 'Sinal Cobre total', 'Sinal Coliformes termotolerantes', 'Sinal Coliformes totais', 'Sinal Condição de tempo', 'Sinal Condutividade elétrica in loco', 'Sinal Condutividade elétrica laboratório', 'Sinal Cor verdadeira', 'Sinal Cromo hexavalente', 'Sinal Cromo total', 'Sinal Cromo trivalente', 'Sinal DDT', 'Sinal Demanda Bioquímica de Oxigênio', 'Sinal Demanda Química de Oxigênio', 'Sinal Densidade de cianobactérias', 'Sinal Descarga Liquida', 'Sinal Dureza de Cálcio', 'Sinal Dureza de magnésio', 'Sinal Dureza total', 'Sinal Endossulfan - alfa + beta', 'Sinal Endrin', 'Sinal Ensaio ecotoxicológico', 'Sinal Escherichia coli', 'Sinal Estanho total', 'Sinal Estreptococos fecais', 'Sinal Fenóis totais', 'Sinal Feoftina a', 'Sinal Ferro dissolvido', 'Sinal Ferro total', 'Sinal Fluoreto ionizado', 'Sinal Fósforo total', 'Sinal Heptacloro epóxido + Heptacloro', 'Sinal Hexaclorobenzeno', 'Sinal Lindano', 'Sinal Magnésio total', 'Sinal Manganês dissolvido', 'Sinal Manganês total', 'Sinal Mercúrio total', 'Sinal Metoxicloro', 'Sinal Microcistina', 'Sinal Molinato', 'Sinal Níquel total', 'Sinal Nitrato', 'Sinal Nitrito', 'Sinal Nitrogênio amoniacal total', 'Sinal Nitrogênio orgânico', 'Sinal Óleos e graxas', 'Sinal Ortofosfato', 'Sinal Oxigênio dissolvido', 'Sinal Pentaclorofenol', 'Sinal Permetrina - cis + trans', 'Sinal pH in loco', 'Sinal pH laboratório', 'Sinal Potássio dissolvido', 'Sinal Potássio total', 'Sinal Precipitação', 'Sinal Profundidade', 'Sinal Saxitoxina', 'Sinal Selênio total', 'Sinal Simazina', 'Sinal Sódio dissolvido', 'Sinal Sódio total', 'Sinal Sólidos dissolvidos totais', 'Sinal Sólidos em suspensão totais', 'Sinal Sólidos sedimentáveis', 'Sinal Sólidos totais', 'Sinal Substâncias tensoativas', 'Sinal Sulfato total', 'Sinal Sulfeto', 'Sinal Temperatura da água', 'Sinal Temperatura do ar', 'Sinal Transparência', 'Sinal Trifluoralina', 'Sinal Turbidez', 'Sinal Vanádio total', 'Sinal Zinco total']

In [ ]:
colunas_valor = [
    c for c in df.columns
    if not c.startswith("Sinal")
]

In [ ]:
# Verificar valores ausentes
missing = df.isna().sum()

missing_percent = (
    df.isna().mean() * 100
).sort_values(ascending=False)

auditoria_missing = pd.DataFrame({
    "missing": missing,
    "missing_percent": missing_percent
})

auditoria_missing.head(20)

                             missing  missing_percent
2,4,6 Triclorofenol            39472        99.639026
Alcalinidade de bicarbonato    21345        53.881106
Alcalinidade total             20865        52.669443
Aldrin + Dieldrin              39473        99.641550
Alumínio dissolvido            25225        63.675375
Alumínio total                 37841        95.521898
Arsênio Dissolvido             37989        95.895494
Arsênio total                  16421        41.451470
Atrazina                       39469        99.631453
Boro dissolvido                35812        90.400101
Boro total                     33061        83.455762
Bário total                    22507        56.814338
Chumbo total                    8971        22.645463
Cianeto Livre                  23216        58.604064
Cianeto total                  31656        79.909125
Clordano - cis + trans         39468        99.628928
Cloreto total                     79         0.199419
Clorofila a                    10235        25.836173
Cobre dissolvido               13766        34.749464
Cobre total                    32695        82.531869

In [ ]:
# Valores ausentes por parâmetro
parametros = [
    "pH in loco",
    "Turbidez",
    "Oxigênio dissolvido",
    "Temperatura da água",
    "Demanda Bioquímica de Oxigênio",
    "Fósforo total",
    "Nitrato"
]

for parametro in parametros:
    percentual = df[parametro].isna().mean() * 100
    print(parametro, round(percentual, 2))

pH in loco 0.23
Turbidez 0.15
Oxigênio dissolvido 0.12
Temperatura da água 0.12
Demanda Bioquímica de Oxigênio 0.78
Fósforo total 0.83
Nitrato 0.86

In [ ]:
# Verificar duplicidade
chave = [
    "Estação",
    "Data de Amostragem",
    "Hora de Amostragem"
]

duplicados = df.duplicated(
    subset=chave,
    keep=False
)

df[duplicados].sort_values(chave)

Empty DataFrame
Columns: [Estação, Data de Amostragem, Hora de Amostragem, Sinal 2,4,6 Triclorofenol, 2,4,6 Triclorofenol, Sinal Alcalinidade de bicarbonato, Alcalinidade de bicarbonato, Sinal Alcalinidade total, Alcalinidade total, Sinal Aldrin + Dieldrin, Aldrin + Dieldrin, Sinal Alumínio dissolvido, Alumínio dissolvido, Sinal Alumínio total, Alumínio total, Sinal Arsênio Dissolvido, Arsênio Dissolvido, Sinal Arsênio total, Arsênio total, Sinal Atrazina, Atrazina, Sinal Bário total, Bário total, Sinal Boro dissolvido, Boro dissolvido, Sinal Boro total, Boro total, Sinal Cádmio total, Cádmio total, Sinal Cálcio total, Cálcio total, Sinal Chumbo total, Chumbo total, Sinal Cianeto Livre, Cianeto Livre, Sinal Cianeto total, Cianeto total, Sinal Clordano - cis + trans, Clordano - cis + trans, Sinal Cloreto total, Cloreto total, Sinal Clorofila a, Clorofila a, Sinal Cobre dissolvido, Cobre dissolvido, Sinal Cobre total, Cobre total, Sinal Coliformes termotolerantes, Coliformes termotolerantes, Sinal Coliformes totais, Coliformes totais, Sinal Condição de tempo, Condição de tempo, Sinal Condutividade elétrica in loco, Condutividade elétrica in loco, Sinal Condutividade elétrica laboratório, Condutividade elétrica laboratório, Sinal Cor verdadeira, Cor verdadeira, Sinal Cromo hexavalente, Cromo hexavalente, Sinal Cromo total, Cromo total, Sinal Cromo trivalente, Cromo trivalente, Sinal DDT, DDT, Sinal Demanda Bioquímica de Oxigênio, Demanda Bioquímica de Oxigênio, Sinal Demanda Química de Oxigênio, Demanda Química de Oxigênio, Sinal Densidade de cianobactérias, Densidade de cianobactérias, Sinal Descarga Liquida, Descarga Liquida, Sinal Dureza de Cálcio, Dureza de Cálcio, Sinal Dureza de magnésio, Dureza de magnésio, Sinal Dureza total, Dureza total, Sinal Endossulfan - alfa + beta, Endossulfan - alfa + beta, Sinal Endrin, Endrin, Sinal Ensaio ecotoxicológico, Ensaio ecotoxicológico, Sinal Escherichia coli, Escherichia coli, Sinal Estanho total, Estanho total, Sinal Estreptococos fecais, Estreptococos fecais, Sinal Fenóis totais, Fenóis totais, Sinal Feoftina a, Feoftina a, Sinal Ferro dissolvido, Ferro dissolvido, Sinal Ferro total, ...]
Index: []

[0 rows x 196 columns]

In [ ]:
print("Registros duplicados:", duplicados.sum())

Registros duplicados: 0

In [ ]:
duplicados_linha = df.duplicated(keep=False)

print("Linhas completamente duplicadas:", duplicados_linha.sum())

Linhas completamente duplicadas: 0

In [ ]:
# Verificar tipos de dados
pd.options.display.max_rows = None
df.dtypes

Estação                                             object
Data de Amostragem                          datetime64[ns]
Hora de Amostragem                                  object
Sinal 2,4,6 Triclorofenol                           object
2,4,6 Triclorofenol                                float64
Sinal Alcalinidade de bicarbonato                   object
Alcalinidade de bicarbonato                        float64
Sinal Alcalinidade total                            object
Alcalinidade total                                 float64
Sinal Aldrin + Dieldrin                             object
Aldrin + Dieldrin                                  float64
Sinal Alumínio dissolvido                           object
Alumínio dissolvido                                float64
Sinal Alumínio total                                object
Alumínio total                                     float64
Sinal Arsênio Dissolvido                            object
Arsênio Dissolvido                                 float64
Sinal Arsênio total                                 object
Arsênio total                                      float64
Sinal Atrazina                                      object
Atrazina                                           float64
Sinal Bário total                                   object
Bário total                                        float64
Sinal Boro dissolvido                               object
Boro dissolvido                                    float64
Sinal Boro total                                    object
Boro total                                         float64
Sinal Cádmio total                                  object
Cádmio total                                       float64
Sinal Cálcio total                                  object
Cálcio total                                       float64
Sinal Chumbo total                                  object
Chumbo total                                       float64
Sinal Cianeto Livre                                 object
Cianeto Livre                                      float64
Sinal Cianeto total                                 object
Cianeto total                                      float64
Sinal Clordano - cis + trans                        object
Clordano - cis + trans                             float64
Sinal Cloreto total                                 object
Cloreto total                                      float64
Sinal Clorofila a                                   object
Clorofila a                                        float64
Sinal Cobre dissolvido                              object
Cobre dissolvido                                   float64
Sinal Cobre total                                   object
Cobre total                                        float64
Sinal Coliformes termotolerantes                    object
Coliformes termotolerantes                         float64
Sinal Coliformes totais                             object
Coliformes totais                                  float64
Sinal Condição de tempo                            float64
Condição de tempo                                   object
Sinal Condutividade elétrica in loco               float64
Condutividade elétrica in loco                     float64
Sinal Condutividade elétrica laboratório           float64
Condutividade elétrica laboratório                 float64
Sinal Cor verdadeira                                object
Cor verdadeira                                     float64
Sinal Cromo hexavalente                             object
Cromo hexavalente                                  float64
Sinal Cromo total                                   object
Cromo total                                        float64
Sinal Cromo trivalente                              object
Cromo trivalente                                   float64
Sinal DDT                                           object
DDT                                                float64
Sinal Demanda Bioquímica de Oxigênio                object
Demanda Bioquímica de Oxigênio                     float64
Sinal Demanda Química de Oxigênio                   object
Demanda Química de Oxigênio                        float64
Sinal Densidade de cianobactérias                   object
Densidade de cianobactérias                        float64
Sinal Descarga Liquida                             float64
Descarga Liquida                                   float64
Sinal Dureza de Cálcio                              object
Dureza de Cálcio                                   float64
Sinal Dureza de magnésio                            object
Dureza de magnésio                                 float64
Sinal Dureza total                                  object
Dureza total                                       float64
Sinal Endossulfan - alfa + beta                     object
Endossulfan - alfa + beta                          float64
Sinal Endrin                                        object
Endrin                                             float64
Sinal Ensaio ecotoxicológico                       float64
Ensaio ecotoxicológico                              object
Sinal Escherichia coli                              object
Escherichia coli                                   float64
Sinal Estanho total                                 object
Estanho total                                      float64
Sinal Estreptococos fecais                          object
Estreptococos fecais                               float64
Sinal Fenóis totais                                 object
Fenóis totais                                      float64
Sinal Feoftina a                                    object
Feoftina a                                         float64
Sinal Ferro dissolvido                              object
Ferro dissolvido                                   float64
Sinal Ferro total                                   object
Ferro total                                        float64
Sinal Fluoreto ionizado                             object
Fluoreto ionizado                                  float64
Sinal Fósforo total                                 object
Fósforo total                                      float64
Sinal Heptacloro epóxido + Heptacloro               object
Heptacloro epóxido + Heptacloro                    float64
Sinal Hexaclorobenzeno                              object
Hexaclorobenzeno                                   float64
Sinal Lindano                                       object
Lindano                                            float64
Sinal Magnésio total                                object
Magnésio total                                     float64
Sinal Manganês dissolvido                          float64
Manganês dissolvido                                float64
Sinal Manganês total                                object
Manganês total                                     float64
Sinal Mercúrio total                                object
Mercúrio total                                     float64
Sinal Metoxicloro                                   object
Metoxicloro                                        float64
Sinal Microcistina                                  object
Microcistina                                       float64
Sinal Molinato                                      object
Molinato                                           float64
Sinal Níquel total                                  object
Níquel total                                       float64
Sinal Nitrato                                       object
Nitrato                                            float64
Sinal Nitrito                                       object
Nitrito                                            float64
Sinal Nitrogênio amoniacal total                    object
Nitrogênio amoniacal total                         float64
Sinal Nitrogênio orgânico                           object
Nitrogênio orgânico                                float64
Sinal Óleos e graxas                                object
Óleos e graxas                                     float64
Sinal Ortofosfato                                   object
Ortofosfato                                        float64
Sinal Oxigênio dissolvido                           object
Oxigênio dissolvido                                float64
Sinal Pentaclorofenol                               object
Pentaclorofenol                                    float64
Sinal Permetrina - cis + trans                      object
Permetrina - cis + trans                           float64
Sinal pH in loco                                   float64
pH in loco                                         float64
Sinal pH laboratório                               float64
pH laboratório                                     float64
Sinal Potássio dissolvido                           object
Potássio dissolvido                                float64
Sinal Potássio total                               float64
Potássio total                                     float64
Sinal Precipitação                                 float64
Precipitação                                       float64
Sinal Profundidade                                 float64
Profundidade                                       float64
Sinal Saxitoxina                                    object
Saxitoxina                                         float64
Sinal Selênio total                                 object
Selênio total                                      float64
Sinal Simazina                                      object
Simazina                                           float64
Sinal Sódio dissolvido                             float64
Sódio dissolvido                                   float64
Sinal Sódio total                                  float64
Sódio total                                        float64
Sinal Sólidos dissolvidos totais                   float64
Sólidos dissolvidos totais                         float64
Sinal Sólidos em suspensão totais                   object
Sólidos em suspensão totais                        float64
Sinal Sólidos sedimentáveis                         object
Sólidos sedimentáveis                              float64
Sinal Sólidos totais                               float64
Sólidos totais                                     float64
Sinal Substâncias tensoativas                       object
Substâncias tensoativas                            float64
Sinal Sulfato total                                 object
Sulfato total                                      float64
Sinal Sulfeto                                       object
Sulfeto                                            float64
Sinal Temperatura da água                          float64
Temperatura da água                                float64
Sinal Temperatura do ar                            float64
Temperatura do ar                                  float64
Sinal Transparência                                float64
Transparência                                      float64
Sinal Trifluoralina                                 object
Trifluoralina                                      float64
Sinal Turbidez                                      object
Turbidez                                           float64
Sinal Vanádio total                                 object
Vanádio total                                      float64
Sinal Zinco total                                   object
Zinco total                                        float64
ano                                                  int32
dtype: object

In [ ]:
# Verificar sinais < e >
for coluna in colunas_sinal:

    valores = df[coluna].dropna().unique()

    print(f"\n{coluna}")
    print(valores)

Sinal 2,4,6 Triclorofenol
['<']

Sinal Alcalinidade de bicarbonato
['<']

Sinal Alcalinidade total
['<']

Sinal Aldrin + Dieldrin
['<']

Sinal Alumínio dissolvido
['<']

Sinal Alumínio total
['<']

Sinal Arsênio Dissolvido
['<']

Sinal Arsênio total
['<']

Sinal Atrazina
['<']

Sinal Bário total
['<']

Sinal Boro dissolvido
['<']

Sinal Boro total
['<']

Sinal Cádmio total
['<']

Sinal Cálcio total
['<']

Sinal Chumbo total
['<']

Sinal Cianeto Livre
['<']

Sinal Cianeto total
['<']

Sinal Clordano - cis + trans
['<']

Sinal Cloreto total
['<']

Sinal Clorofila a
['<']

Sinal Cobre dissolvido
['<']

Sinal Cobre total
['<']

Sinal Coliformes termotolerantes
['<' '>']

Sinal Coliformes totais
['>' '<']

Sinal Condição de tempo
[]

Sinal Condutividade elétrica in loco
[]

Sinal Condutividade elétrica laboratório
[]

Sinal Cor verdadeira
['<']

Sinal Cromo hexavalente
['<']

Sinal Cromo total
['<']

Sinal Cromo trivalente
['<']

Sinal DDT
['<']

Sinal Demanda Bioquímica de Oxigênio
['<']

Sinal Demanda Química de Oxigênio
['<']

Sinal Densidade de cianobactérias
['<']

Sinal Descarga Liquida
[]

Sinal Dureza de Cálcio
['<']

Sinal Dureza de magnésio
['<']

Sinal Dureza total
['<']

Sinal Endossulfan - alfa + beta
['<']

Sinal Endrin
['<']

Sinal Ensaio ecotoxicológico
[]

Sinal Escherichia coli
['>' '<']

Sinal Estanho total
['<']

Sinal Estreptococos fecais
['<' '>']

Sinal Fenóis totais
['<']

Sinal Feoftina a
['<']

Sinal Ferro dissolvido
['<']

Sinal Ferro total
['<']

Sinal Fluoreto ionizado
['<']

Sinal Fósforo total
['<']

Sinal Heptacloro epóxido + Heptacloro
['<']

Sinal Hexaclorobenzeno
['<']

Sinal Lindano
['<']

Sinal Magnésio total
['<']

Sinal Manganês dissolvido
[]

Sinal Manganês total
['<']

Sinal Mercúrio total
['<']

Sinal Metoxicloro
['<']

Sinal Microcistina
['<']

Sinal Molinato
['<']

Sinal Níquel total
['<']

Sinal Nitrato
['<']

Sinal Nitrito
['<']

Sinal Nitrogênio amoniacal total
['<']

Sinal Nitrogênio orgânico
['<']

Sinal Óleos e graxas
['<']

Sinal Ortofosfato
['<']

Sinal Oxigênio dissolvido
['<']

Sinal Pentaclorofenol
['<']

Sinal Permetrina - cis + trans
['<']

Sinal pH in loco
[]

Sinal pH laboratório
[]

Sinal Potássio dissolvido
['<']

Sinal Potássio total
[]

Sinal Precipitação
[]

Sinal Profundidade
[]

Sinal Saxitoxina
['<']

Sinal Selênio total
['<']

Sinal Simazina
['<']

Sinal Sódio dissolvido
[]

Sinal Sódio total
[]

Sinal Sólidos dissolvidos totais
[]

Sinal Sólidos em suspensão totais
['<']

Sinal Sólidos sedimentáveis
['<']

Sinal Sólidos totais
[]

Sinal Substâncias tensoativas
['<']

Sinal Sulfato total
['<']

Sinal Sulfeto
['<']

Sinal Temperatura da água
[]

Sinal Temperatura do ar
[]

Sinal Transparência
[]

Sinal Trifluoralina
['<']

Sinal Turbidez
['<']

Sinal Vanádio total
['<']

Sinal Zinco total
['<']

In [ ]:
for coluna in colunas_sinal:

    print(
        coluna,
        df[coluna].value_counts(dropna=False)
    )

Sinal 2,4,6 Triclorofenol Sinal 2,4,6 Triclorofenol
NaN    39472
<        143
Name: count, dtype: int64
Sinal Alcalinidade de bicarbonato Sinal Alcalinidade de bicarbonato
NaN    39601
<         14
Name: count, dtype: int64
Sinal Alcalinidade total Sinal Alcalinidade total
NaN    39601
<         14
Name: count, dtype: int64
Sinal Aldrin + Dieldrin Sinal Aldrin + Dieldrin
NaN    39473
<        142
Name: count, dtype: int64
Sinal Alumínio dissolvido Sinal Alumínio dissolvido
NaN    30431
<       9184
Name: count, dtype: int64
Sinal Alumínio total Sinal Alumínio total
NaN    39577
<         38
Name: count, dtype: int64
Sinal Arsênio Dissolvido Sinal Arsênio Dissolvido
NaN    39079
<        536
Name: count, dtype: int64
Sinal Arsênio total Sinal Arsênio total
NaN    22571
<      17044
Name: count, dtype: int64
Sinal Atrazina Sinal Atrazina
NaN    39469
<        146
Name: count, dtype: int64
Sinal Bário total Sinal Bário total
NaN    37936
<       1679
Name: count, dtype: int64
Sinal Boro dissolvido Sinal Boro dissolvido
NaN    35876
<       3739
Name: count, dtype: int64
Sinal Boro total Sinal Boro total
NaN    33129
<       6486
Name: count, dtype: int64
Sinal Cádmio total Sinal Cádmio total
<      27900
NaN    11715
Name: count, dtype: int64
Sinal Cálcio total Sinal Cálcio total
NaN    39576
<         39
Name: count, dtype: int64
Sinal Chumbo total Sinal Chumbo total
<      25972
NaN    13643
Name: count, dtype: int64
Sinal Cianeto Livre Sinal Cianeto Livre
NaN    28347
<      11268
Name: count, dtype: int64
Sinal Cianeto total Sinal Cianeto total
NaN    31968
<       7647
Name: count, dtype: int64
Sinal Clordano - cis + trans Sinal Clordano - cis + trans
NaN    39468
<        147
Name: count, dtype: int64
Sinal Cloreto total Sinal Cloreto total
NaN    37498
<       2117
Name: count, dtype: int64
Sinal Clorofila a Sinal Clorofila a
NaN    35042
<       4573
Name: count, dtype: int64
Sinal Cobre dissolvido Sinal Cobre dissolvido
<      24074
NaN    15541
Name: count, dtype: int64
Sinal Cobre total Sinal Cobre total
NaN    35208
<       4407
Name: count, dtype: int64
Sinal Coliformes termotolerantes Sinal Coliformes termotolerantes
NaN    37515
>       1578
<        522
Name: count, dtype: int64
Sinal Coliformes totais Sinal Coliformes totais
NaN    30322
>       9091
<        202
Name: count, dtype: int64
Sinal Condição de tempo Sinal Condição de tempo
NaN    39615
Name: count, dtype: int64
Sinal Condutividade elétrica in loco Sinal Condutividade elétrica in loco
NaN    39615
Name: count, dtype: int64
Sinal Condutividade elétrica laboratório Sinal Condutividade elétrica laboratório
NaN    39615
Name: count, dtype: int64
Sinal Cor verdadeira Sinal Cor verdadeira
NaN    36869
<       2746
Name: count, dtype: int64
Sinal Cromo hexavalente Sinal Cromo hexavalente
NaN    34341
<       5274
Name: count, dtype: int64
Sinal Cromo total Sinal Cromo total
<      22950
NaN    16665
Name: count, dtype: int64
Sinal Cromo trivalente Sinal Cromo trivalente
NaN    36079
<       3536
Name: count, dtype: int64
Sinal DDT Sinal DDT
NaN    39468
<        147
Name: count, dtype: int64
Sinal Demanda Bioquímica de Oxigênio Sinal Demanda Bioquímica de Oxigênio
<      26008
NaN    13607
Name: count, dtype: int64
Sinal Demanda Química de Oxigênio Sinal Demanda Química de Oxigênio
NaN    35470
<       4145
Name: count, dtype: int64
Sinal Densidade de cianobactérias Sinal Densidade de cianobactérias
NaN    39329
<        286
Name: count, dtype: int64
Sinal Descarga Liquida Sinal Descarga Liquida
NaN    39615
Name: count, dtype: int64
Sinal Dureza de Cálcio Sinal Dureza de Cálcio
NaN    39574
<         41
Name: count, dtype: int64
Sinal Dureza de magnésio Sinal Dureza de magnésio
NaN    39454
<        161
Name: count, dtype: int64
Sinal Dureza total Sinal Dureza total
NaN    39605
<         10
Name: count, dtype: int64
Sinal Endossulfan - alfa + beta Sinal Endossulfan - alfa + beta
NaN    39469
<        146
Name: count, dtype: int64
Sinal Endrin Sinal Endrin
NaN    39470
<        145
Name: count, dtype: int64
Sinal Ensaio ecotoxicológico Sinal Ensaio ecotoxicológico
NaN    39615
Name: count, dtype: int64
Sinal Escherichia coli Sinal Escherichia coli
NaN    37387
>       1839
<        389
Name: count, dtype: int64
Sinal Estanho total Sinal Estanho total
NaN    38595
<       1020
Name: count, dtype: int64
Sinal Estreptococos fecais Sinal Estreptococos fecais
NaN    38816
>        529
<        270
Name: count, dtype: int64
Sinal Fenóis totais Sinal Fenóis totais
<      23712
NaN    15903
Name: count, dtype: int64
Sinal Feoftina a Sinal Feoftina a
NaN    37304
<       2311
Name: count, dtype: int64
Sinal Ferro dissolvido Sinal Ferro dissolvido
NaN    37797
<       1818
Name: count, dtype: int64
Sinal Ferro total Sinal Ferro total
NaN    39603
<         12
Name: count, dtype: int64
Sinal Fluoreto ionizado Sinal Fluoreto ionizado
NaN    39529
<         86
Name: count, dtype: int64
Sinal Fósforo total Sinal Fósforo total
NaN    33386
<       6229
Name: count, dtype: int64
Sinal Heptacloro epóxido + Heptacloro Sinal Heptacloro epóxido + Heptacloro
NaN    39469
<        146
Name: count, dtype: int64
Sinal Hexaclorobenzeno Sinal Hexaclorobenzeno
NaN    39469
<        146
Name: count, dtype: int64
Sinal Lindano Sinal Lindano
NaN    39469
<        146
Name: count, dtype: int64
Sinal Magnésio total Sinal Magnésio total
NaN    39501
<        114
Name: count, dtype: int64
Sinal Manganês dissolvido Sinal Manganês dissolvido
NaN    39615
Name: count, dtype: int64
Sinal Manganês total Sinal Manganês total
NaN    38895
<        720
Name: count, dtype: int64
Sinal Mercúrio total Sinal Mercúrio total
<      22682
NaN    16933
Name: count, dtype: int64
Sinal Metoxicloro Sinal Metoxicloro
NaN    39469
<        146
Name: count, dtype: int64
Sinal Microcistina Sinal Microcistina
NaN    39333
<        282
Name: count, dtype: int64
Sinal Molinato Sinal Molinato
NaN    39482
<        133
Name: count, dtype: int64
Sinal Níquel total Sinal Níquel total
NaN    19922
<      19693
Name: count, dtype: int64
Sinal Nitrato Sinal Nitrato
NaN    37494
<       2121
Name: count, dtype: int64
Sinal Nitrito Sinal Nitrito
NaN    38882
<        733
Name: count, dtype: int64
Sinal Nitrogênio amoniacal total Sinal Nitrogênio amoniacal total
NaN    24146
<      15469
Name: count, dtype: int64
Sinal Nitrogênio orgânico Sinal Nitrogênio orgânico
NaN    36892
<       2723
Name: count, dtype: int64
Sinal Óleos e graxas Sinal Óleos e graxas
NaN    24490
<      15125
Name: count, dtype: int64
Sinal Ortofosfato Sinal Ortofosfato
NaN    39465
<        150
Name: count, dtype: int64
Sinal Oxigênio dissolvido Sinal Oxigênio dissolvido
NaN    39444
<        171
Name: count, dtype: int64
Sinal Pentaclorofenol Sinal Pentaclorofenol
NaN    39524
<         91
Name: count, dtype: int64
Sinal Permetrina - cis + trans Sinal Permetrina - cis + trans
NaN    39469
<        146
Name: count, dtype: int64
Sinal pH in loco Sinal pH in loco
NaN    39615
Name: count, dtype: int64
Sinal pH laboratório Sinal pH laboratório
NaN    39615
Name: count, dtype: int64
Sinal Potássio dissolvido Sinal Potássio dissolvido
NaN    39599
<         16
Name: count, dtype: int64
Sinal Potássio total Sinal Potássio total
NaN    39615
Name: count, dtype: int64
Sinal Precipitação Sinal Precipitação
NaN    39615
Name: count, dtype: int64
Sinal Profundidade Sinal Profundidade
NaN    39615
Name: count, dtype: int64
Sinal Saxitoxina Sinal Saxitoxina
NaN    39451
<        164
Name: count, dtype: int64
Sinal Selênio total Sinal Selênio total
NaN    28923
<      10692
Name: count, dtype: int64
Sinal Simazina Sinal Simazina
NaN    39469
<        146
Name: count, dtype: int64
Sinal Sódio dissolvido Sinal Sódio dissolvido
NaN    39615
Name: count, dtype: int64
Sinal Sódio total Sinal Sódio total
NaN    39615
Name: count, dtype: int64
Sinal Sólidos dissolvidos totais Sinal Sólidos dissolvidos totais
NaN    39615
Name: count, dtype: int64
Sinal Sólidos em suspensão totais Sinal Sólidos em suspensão totais
NaN    38438
<       1177
Name: count, dtype: int64
Sinal Sólidos sedimentáveis Sinal Sólidos sedimentáveis
NaN    39046
<        569
Name: count, dtype: int64
Sinal Sólidos totais Sinal Sólidos totais
NaN    39615
Name: count, dtype: int64
Sinal Substâncias tensoativas Sinal Substâncias tensoativas
<      20439
NaN    19176
Name: count, dtype: int64
Sinal Sulfato total Sinal Sulfato total
NaN    30628
<       8987
Name: count, dtype: int64
Sinal Sulfeto Sinal Sulfeto
NaN    21036
<      18579
Name: count, dtype: int64
Sinal Temperatura da água Sinal Temperatura da água
NaN    39615
Name: count, dtype: int64
Sinal Temperatura do ar Sinal Temperatura do ar
NaN    39615
Name: count, dtype: int64
Sinal Transparência Sinal Transparência
NaN    39615
Name: count, dtype: int64
Sinal Trifluoralina Sinal Trifluoralina
NaN    39469
<        146
Name: count, dtype: int64
Sinal Turbidez Sinal Turbidez
NaN    39588
<         27
Name: count, dtype: int64
Sinal Vanádio total Sinal Vanádio total
NaN    39601
<         14
Name: count, dtype: int64
Sinal Zinco total Sinal Zinco total
NaN    26111
<      13504
Name: count, dtype: int64

In [ ]:
# Verificar valores impossíveis
df["pH in loco"].describe()

count    39525.000000
mean         6.903609
std          0.592999
min          2.900000
25%          6.500000
50%          6.900000
75%          7.300000
max         11.400000
Name: pH in loco, dtype: float64

In [ ]:
df[
    (df["pH in loco"] < 0) |
    (df["pH in loco"] > 14)
]

Empty DataFrame
Columns: [Estação, Data de Amostragem, Hora de Amostragem, Sinal 2,4,6 Triclorofenol, 2,4,6 Triclorofenol, Sinal Alcalinidade de bicarbonato, Alcalinidade de bicarbonato, Sinal Alcalinidade total, Alcalinidade total, Sinal Aldrin + Dieldrin, Aldrin + Dieldrin, Sinal Alumínio dissolvido, Alumínio dissolvido, Sinal Alumínio total, Alumínio total, Sinal Arsênio Dissolvido, Arsênio Dissolvido, Sinal Arsênio total, Arsênio total, Sinal Atrazina, Atrazina, Sinal Bário total, Bário total, Sinal Boro dissolvido, Boro dissolvido, Sinal Boro total, Boro total, Sinal Cádmio total, Cádmio total, Sinal Cálcio total, Cálcio total, Sinal Chumbo total, Chumbo total, Sinal Cianeto Livre, Cianeto Livre, Sinal Cianeto total, Cianeto total, Sinal Clordano - cis + trans, Clordano - cis + trans, Sinal Cloreto total, Cloreto total, Sinal Clorofila a, Clorofila a, Sinal Cobre dissolvido, Cobre dissolvido, Sinal Cobre total, Cobre total, Sinal Coliformes termotolerantes, Coliformes termotolerantes, Sinal Coliformes totais, Coliformes totais, Sinal Condição de tempo, Condição de tempo, Sinal Condutividade elétrica in loco, Condutividade elétrica in loco, Sinal Condutividade elétrica laboratório, Condutividade elétrica laboratório, Sinal Cor verdadeira, Cor verdadeira, Sinal Cromo hexavalente, Cromo hexavalente, Sinal Cromo total, Cromo total, Sinal Cromo trivalente, Cromo trivalente, Sinal DDT, DDT, Sinal Demanda Bioquímica de Oxigênio, Demanda Bioquímica de Oxigênio, Sinal Demanda Química de Oxigênio, Demanda Química de Oxigênio, Sinal Densidade de cianobactérias, Densidade de cianobactérias, Sinal Descarga Liquida, Descarga Liquida, Sinal Dureza de Cálcio, Dureza de Cálcio, Sinal Dureza de magnésio, Dureza de magnésio, Sinal Dureza total, Dureza total, Sinal Endossulfan - alfa + beta, Endossulfan - alfa + beta, Sinal Endrin, Endrin, Sinal Ensaio ecotoxicológico, Ensaio ecotoxicológico, Sinal Escherichia coli, Escherichia coli, Sinal Estanho total, Estanho total, Sinal Estreptococos fecais, Estreptococos fecais, Sinal Fenóis totais, Fenóis totais, Sinal Feoftina a, Feoftina a, Sinal Ferro dissolvido, Ferro dissolvido, Sinal Ferro total, ...]
Index: []

[0 rows x 196 columns]

In [ ]:
# Parâmetros que não podem ser negativos'
df[df["Turbidez"] < 0]

Empty DataFrame
Columns: [Estação, Data de Amostragem, Hora de Amostragem, Sinal 2,4,6 Triclorofenol, 2,4,6 Triclorofenol, Sinal Alcalinidade de bicarbonato, Alcalinidade de bicarbonato, Sinal Alcalinidade total, Alcalinidade total, Sinal Aldrin + Dieldrin, Aldrin + Dieldrin, Sinal Alumínio dissolvido, Alumínio dissolvido, Sinal Alumínio total, Alumínio total, Sinal Arsênio Dissolvido, Arsênio Dissolvido, Sinal Arsênio total, Arsênio total, Sinal Atrazina, Atrazina, Sinal Bário total, Bário total, Sinal Boro dissolvido, Boro dissolvido, Sinal Boro total, Boro total, Sinal Cádmio total, Cádmio total, Sinal Cálcio total, Cálcio total, Sinal Chumbo total, Chumbo total, Sinal Cianeto Livre, Cianeto Livre, Sinal Cianeto total, Cianeto total, Sinal Clordano - cis + trans, Clordano - cis + trans, Sinal Cloreto total, Cloreto total, Sinal Clorofila a, Clorofila a, Sinal Cobre dissolvido, Cobre dissolvido, Sinal Cobre total, Cobre total, Sinal Coliformes termotolerantes, Coliformes termotolerantes, Sinal Coliformes totais, Coliformes totais, Sinal Condição de tempo, Condição de tempo, Sinal Condutividade elétrica in loco, Condutividade elétrica in loco, Sinal Condutividade elétrica laboratório, Condutividade elétrica laboratório, Sinal Cor verdadeira, Cor verdadeira, Sinal Cromo hexavalente, Cromo hexavalente, Sinal Cromo total, Cromo total, Sinal Cromo trivalente, Cromo trivalente, Sinal DDT, DDT, Sinal Demanda Bioquímica de Oxigênio, Demanda Bioquímica de Oxigênio, Sinal Demanda Química de Oxigênio, Demanda Química de Oxigênio, Sinal Densidade de cianobactérias, Densidade de cianobactérias, Sinal Descarga Liquida, Descarga Liquida, Sinal Dureza de Cálcio, Dureza de Cálcio, Sinal Dureza de magnésio, Dureza de magnésio, Sinal Dureza total, Dureza total, Sinal Endossulfan - alfa + beta, Endossulfan - alfa + beta, Sinal Endrin, Endrin, Sinal Ensaio ecotoxicológico, Ensaio ecotoxicológico, Sinal Escherichia coli, Escherichia coli, Sinal Estanho total, Estanho total, Sinal Estreptococos fecais, Estreptococos fecais, Sinal Fenóis totais, Fenóis totais, Sinal Feoftina a, Feoftina a, Sinal Ferro dissolvido, Ferro dissolvido, Sinal Ferro total, ...]
Index: []

[0 rows x 196 columns]

In [ ]:
df[df["Temperatura da água"] < 0]

Empty DataFrame
Columns: [Estação, Data de Amostragem, Hora de Amostragem, Sinal 2,4,6 Triclorofenol, 2,4,6 Triclorofenol, Sinal Alcalinidade de bicarbonato, Alcalinidade de bicarbonato, Sinal Alcalinidade total, Alcalinidade total, Sinal Aldrin + Dieldrin, Aldrin + Dieldrin, Sinal Alumínio dissolvido, Alumínio dissolvido, Sinal Alumínio total, Alumínio total, Sinal Arsênio Dissolvido, Arsênio Dissolvido, Sinal Arsênio total, Arsênio total, Sinal Atrazina, Atrazina, Sinal Bário total, Bário total, Sinal Boro dissolvido, Boro dissolvido, Sinal Boro total, Boro total, Sinal Cádmio total, Cádmio total, Sinal Cálcio total, Cálcio total, Sinal Chumbo total, Chumbo total, Sinal Cianeto Livre, Cianeto Livre, Sinal Cianeto total, Cianeto total, Sinal Clordano - cis + trans, Clordano - cis + trans, Sinal Cloreto total, Cloreto total, Sinal Clorofila a, Clorofila a, Sinal Cobre dissolvido, Cobre dissolvido, Sinal Cobre total, Cobre total, Sinal Coliformes termotolerantes, Coliformes termotolerantes, Sinal Coliformes totais, Coliformes totais, Sinal Condição de tempo, Condição de tempo, Sinal Condutividade elétrica in loco, Condutividade elétrica in loco, Sinal Condutividade elétrica laboratório, Condutividade elétrica laboratório, Sinal Cor verdadeira, Cor verdadeira, Sinal Cromo hexavalente, Cromo hexavalente, Sinal Cromo total, Cromo total, Sinal Cromo trivalente, Cromo trivalente, Sinal DDT, DDT, Sinal Demanda Bioquímica de Oxigênio, Demanda Bioquímica de Oxigênio, Sinal Demanda Química de Oxigênio, Demanda Química de Oxigênio, Sinal Densidade de cianobactérias, Densidade de cianobactérias, Sinal Descarga Liquida, Descarga Liquida, Sinal Dureza de Cálcio, Dureza de Cálcio, Sinal Dureza de magnésio, Dureza de magnésio, Sinal Dureza total, Dureza total, Sinal Endossulfan - alfa + beta, Endossulfan - alfa + beta, Sinal Endrin, Endrin, Sinal Ensaio ecotoxicológico, Ensaio ecotoxicológico, Sinal Escherichia coli, Escherichia coli, Sinal Estanho total, Estanho total, Sinal Estreptococos fecais, Estreptococos fecais, Sinal Fenóis totais, Fenóis totais, Sinal Feoftina a, Feoftina a, Sinal Ferro dissolvido, Ferro dissolvido, Sinal Ferro total, ...]
Index: []

[0 rows x 196 columns]

In [ ]:
# Identificação de valores extremos pelo método do IQR
#
# O IQR é utilizado como mecanismo de detecção de candidatos a valores extremos,
# e não como regra automática de exclusão.

outliers_iqr = {}

for parametro in parametros:
    serie = df[parametro].dropna()

    Q1 = serie.quantile(0.25)
    Q3 = serie.quantile(0.75)
    IQR = Q3 - Q1

    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    outliers = serie[j
        (serie < limite_inferior) |
        (serie > limite_superior)
    ]

    outliers_iqr[parametro] = {
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "limite_inferior": limite_inferior,
        "limite_superior": limite_superior,
        "n_outliers": len(outliers),
        "percentual_outliers": len(outliers) / len(serie) * 100
    }

auditoria_outliers = pd.DataFrame(outliers_iqr).T

auditoria_outliers.sort_values(
    "percentual_outliers",
    ascending=False
)

,Q1,Q3,IQR,limite_inferior,limite_superior,n_outliers,percentual_outliers
Demanda Bioquímica de Oxigênio,2.00,2.80,0.80,0.800,4.000,7280.0,18.521817
Nitrogênio amoniacal total,0.10,0.30,0.20,-0.200,0.600,6327.0,16.486867
Coliformes termotolerantes,220.00,13000.00,12780.00,-18950.000,32170.000,3219.0,14.617201
Turbidez,8.11,50.50,42.39,-55.475,114.085,5318.0,13.444231
Fósforo total,0.02,0.12,0.10,-0.130,0.270,4442.0,11.306251
Condutividade elétrica in loco,38.70,134.00,95.30,-104.250,276.950,4360.0,11.048884
Oxigênio dissolvido,6.30,7.80,1.50,4.050,10.050,4066.0,10.276240
Nitrato,0.11,0.68,0.57,-0.745,1.535,3189.0,8.119462
Sólidos totais,57.00,180.00,123.00,-127.500,364.500,3097.0,7.947547
pH in loco,6.50,7.30,0.80,5.300,8.500,625.0,1.581278
Temperatura da água,21.70,26.30,4.60,14.800,33.200,281.0,0.710206

In [ ]:
# Estatísticas descritivas dos parâmetros selecionados
#
# Conjunto reduzido de parâmetros para a auditoria exploratória.
#
# Critérios de seleção:
# 1. relevância para a caracterização da qualidade da água;
# 2. relação com parâmetros utilizados pelo IGAM no IQA;
# 3. elevada cobertura na série histórica;
# 4. diversidade de dimensões físico-químicas e microbiológicas;
# 5. tamanho reduzido para facilitar a demonstração do sistema.
#
# A seleção não representa todos os parâmetros disponíveis na base.
# Os demais parâmetros serão preservados e poderão ser analisados
# posteriormente conforme a pergunta e a disponibilidade dos dados.

parametros = [
    "pH in loco",
    "Turbidez",
    "Oxigênio dissolvido",
    "Temperatura da água",
    "Condutividade elétrica in loco",
    "Demanda Bioquímica de Oxigênio",
    "Fósforo total",
    "Nitrato",
    "Sólidos totais",
    "Nitrogênio amoniacal total",
    "Coliformes termotolerantes"
]

estatisticas = df[parametros].describe().T

estatisticas

,count,mean,std,min,25%,50%,75%,max
pH in loco,39525.0,6.903609,0.592999,2.900,6.50,6.90,7.30,11.40
Turbidez,39556.0,84.677701,339.992420,0.290,8.11,18.60,50.50,17949.00
Oxigênio dissolvido,39567.0,6.736790,1.833971,0.200,6.30,7.20,7.80,18.60
Temperatura da água,39566.0,23.915248,3.461307,0.140,21.70,24.10,26.30,39.80
Condutividade elétrica in loco,39461.0,124.289372,185.582486,0.450,38.70,62.80,134.00,3800.00
Demanda Bioquímica de Oxigênio,39305.0,5.706409,20.042314,0.100,2.00,2.00,2.80,921.00
Fósforo total,39288.0,0.139464,0.297831,0.010,0.02,0.05,0.12,9.24
Nitrato,39276.0,0.597732,1.073309,0.002,0.11,0.28,0.68,34.70
Sólidos totais,38968.0,168.111856,292.111055,6.000,57.00,94.00,180.00,11490.00
Nitrogênio amoniacal total,38376.0,1.119940,3.909856,0.020,0.10,0.11,0.30,99.70
Coliformes termotolerantes,22022.0,22621.256652,55345.757474,2.000,220.00,1700.00,13000.00,2400000.00

In [ ]:
# Cobertura dos parâmetros

total_registros = len(df)

auditoria_parametros = estatisticas.copy()

auditoria_parametros["missing"] = (
    total_registros - auditoria_parametros["count"]
)

auditoria_parametros["cobertura_%"] = (
    auditoria_parametros["count"] / total_registros * 100
)

auditoria_parametros["missing_%"] = (
    auditoria_parametros["missing"] / total_registros * 100
)

auditoria_parametros[
    ["count", "missing", "cobertura_%", "missing_%"]
].sort_values(
    "cobertura_%"
)

                                  count  missing  cobertura_%  missing_%
Coliformes termotolerantes      22022.0  17593.0    55.590054  44.409946
Nitrogênio amoniacal total      38376.0   1239.0    96.872397   3.127603
Sólidos totais                  38968.0    647.0    98.366780   1.633220
Nitrato                         39276.0    339.0    99.144264   0.855736
Fósforo total                   39288.0    327.0    99.174555   0.825445
Demanda Bioquímica de Oxigênio  39305.0    310.0    99.217468   0.782532
Condutividade elétrica in loco  39461.0    154.0    99.611258   0.388742
pH in loco                      39525.0     90.0    99.772813   0.227187
Turbidez                        39556.0     59.0    99.851067   0.148933
Temperatura da água             39566.0     49.0    99.876309   0.123691
Oxigênio dissolvido             39567.0     48.0    99.878834   0.121166

Os parâmetros selecionados apresentam elevada cobertura na série histórica, com exceção de coliformes termotolerantes, que possui 55,59% de cobertura. A diferença de completude deve ser considerada antes de análises que dependam desse parâmetro. A ausência dos dados não será tratada automaticamente como erro ou imputada nesta etapa.

In [ ]:
# Análise de valores ausentes por ano para todos os parâmetros

df["ano"] = df["Data de Amostragem"].dt.year

ausencia_por_ano = (
    df.groupby("ano")[parametros]
      .apply(lambda grupo: grupo.isna().mean() * 100)
)

ausencia_por_ano

,pH in loco,Turbidez,Oxigênio dissolvido,Temperatura da água,Condutividade elétrica in loco,Demanda Bioquímica de Oxigênio,Fósforo total,Nitrato,Sólidos totais,Nitrogênio amoniacal total,Coliformes termotolerantes
ano,,,,,,,,,,,
1997,0.000000,0.000000,0.000000,0.000000,10.688836,1.187648,4.038005,0.712589,23.752969,0.000000,0.000000
1998,0.000000,0.000000,0.000000,0.000000,0.000000,0.671141,0.000000,0.000000,0.000000,0.000000,0.805369
1999,0.000000,0.000000,0.000000,0.000000,0.000000,0.251572,0.000000,0.000000,0.000000,0.000000,0.125786
2000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.103950,0.000000,0.000000,1.039501
2002,0.000000,0.000000,0.000000,0.000000,0.000000,1.338826,1.235839,1.235839,0.000000,1.235839,0.411946
2003,0.000000,0.086281,0.000000,0.000000,0.000000,4.831752,4.831752,4.831752,0.172563,4.831752,1.294219
2004,0.000000,0.086133,0.000000,0.000000,0.000000,4.823428,4.823428,4.823428,0.086133,4.823428,1.119724
2005,0.000000,0.000000,0.086505,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.276817
2006,0.000000,0.151286,0.000000,0.000000,0.605144,0.302572,0.075643,5.673222,0.151286,3.101362,3.555219
2007,0.000000,0.000000,0.000000,0.000000,0.065189,1.825293,1.564537,3.063885,5.019557,5.867014,15.384615
2008,0.000000,0.000000,0.000000,0.000000,0.000000,1.086366,1.520913,0.434546,4.073873,8.908202,2.390005
2009,0.000000,0.000000,0.000000,0.000000,0.000000,0.778589,1.167883,0.389294,3.600973,11.484185,0.973236
2010,0.000000,0.091617,0.000000,0.000000,0.366468,0.732936,1.007787,0.458085,4.489235,11.131470,3.252405
2011,0.043309,0.043309,0.043309,0.043309,0.043309,0.736249,0.736249,0.216544,4.720658,9.008229,0.692941
2012,0.000000,0.125733,0.000000,0.000000,0.000000,0.502934,0.502934,0.167645,1.886002,2.975692,0.293378
2013,0.116009,0.077340,0.077340,0.077340,0.232019,0.077340,0.077340,0.077340,0.657386,0.232019,76.256767
2014,0.189609,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000
2015,1.104341,0.000000,0.000000,0.000000,0.723534,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000
2016,0.157356,0.157356,0.196696,0.157356,0.511408,0.393391,0.393391,0.393391,0.157356,0.393391,100.000000
2017,0.057670,0.057670,0.057670,0.057670,0.057670,0.173010,0.173010,0.173010,0.057670,0.173010,100.000000
2018,1.275046,1.420765,1.275046,1.384335,1.092896,1.420765,1.347905,1.202186,1.420765,1.347905,100.000000
2019,0.430725,0.107681,0.107681,0.107681,0.789663,0.215363,0.215363,0.215363,0.107681,0.215363,100.000000

In [ ]:
# Maior percentual de ausência observado por parâmetro

maior_ausencia = pd.DataFrame({
    "maior_missing_%": ausencia_por_ano.max(),
    "ano_maior_missing": ausencia_por_ano.idxmax()
})

maior_ausencia.sort_values(
    "maior_missing_%",
    ascending=False
)

                                maior_missing_%  ano_maior_missing
Coliformes termotolerantes           100.000000               2014
Sólidos totais                        23.752969               1997
Nitrogênio amoniacal total            11.484185               2009
Condutividade elétrica in loco        10.688836               1997
Nitrato                                5.673222               2006
Fósforo total                          4.831752               2003
Demanda Bioquímica de Oxigênio         4.831752               2003
Turbidez                               1.420765               2018
Temperatura da água                    1.384335               2018
Oxigênio dissolvido                    1.275046               2018
pH in loco                             1.275046               2018

In [ ]:
# Quantidade de registros por ano

registros_por_ano = (
    df["ano"]
    .value_counts()
    .sort_index()
)

registros_por_ano

ano
1997     421
1998     745
1999     795
2000     959
2001     962
2002     971
2003    1159
2004    1161
2005    1156
2006    1322
2007    1534
2008    1841
2009    2055
2010    2183
2011    2309
2012    2386
2013    2586
2014    2637
2015    2626
2016    2542
2017    1734
2018    2745
2019    2786
Name: count, dtype: int64

In [ ]:
# Verificar os registros de 2014

df_2014 = df[df["ano"] == 2014]

print("Registros em 2014:", len(df_2014))
print(
    "Coliformes preenchidos:",
    df_2014["Coliformes termotolerantes"].notna().sum()
)
print(
    "Coliformes ausentes:",
    df_2014["Coliformes termotolerantes"].isna().sum()
)

Registros em 2014: 2637
Coliformes preenchidos: 0
Coliformes ausentes: 2637

O parâmetro Coliformes termotolerantes apresenta ausência de dados em 100% dos 2.637 registros referentes ao ano de 2014. A causa dessa ausência não é determinada pela base analisada e requer investigação adicional.

In [ ]:
# Coliformes termotolerantes em 2014 por estação

coliformes_2014_estacao = (
    df_2014.groupby("Estação")["Coliformes termotolerantes"]
    .agg(
        registros="size",
        preenchidos="count"
    )
)

coliformes_2014_estacao["ausentes"] = (
    coliformes_2014_estacao["registros"]
    - coliformes_2014_estacao["preenchidos"]
)

coliformes_2014_estacao["missing_%"] = (
    coliformes_2014_estacao["ausentes"]
    / coliformes_2014_estacao["registros"]
    * 100
)

coliformes_2014_estacao

         registros  preenchidos  ausentes  missing_%
Estação
AV007            4            0         4      100.0
AV010            4            0         4      100.0
AV020            4            0         4      100.0
AV050            4            0         4      100.0
AV060            4            0         4      100.0
AV070            4            0         4      100.0
AV080            4            0         4      100.0
AV120            4            0         4      100.0
AV160E           2            0         2      100.0
AV180E           2            0         2      100.0
AV200            4            0         4      100.0
AV210           12            0        12      100.0
AV250            4            0         4      100.0
AV300            4            0         4      100.0
AV320            4            0         4      100.0
AV340            4            0         4      100.0
BG001            4            0         4      100.0
BG003            4            0         4      100.0
BG005            4            0         4      100.0
BG007            4            0         4      100.0
BG008            4            0         4      100.0
BG009            4            0         4      100.0
BG011            4            0         4      100.0
BG012            4            0         4      100.0
BG013            4            0         4      100.0
BG014            4            0         4      100.0
BG015            4            0         4      100.0
BG017            4            0         4      100.0
BG019            4            0         4      100.0
BG021            4            0         4      100.0
BG023            4            0         4      100.0
BG024            4            0         4      100.0
BG025            4            0         4      100.0
BG026            4            0         4      100.0
BG027            4            0         4      100.0
BG028            4            0         4      100.0
BG029            4            0         4      100.0
BG030            4            0         4      100.0
BG031            4            0         4      100.0
BG032            4            0         4      100.0
BG033            4            0         4      100.0
BG034            4            0         4      100.0
BG035            4            0         4      100.0
BG036            4            0         4      100.0
BG037            4            0         4      100.0
BG038            4            0         4      100.0
BG039            4            0         4      100.0
BG040            4            0         4      100.0
BG041            4            0         4      100.0
BG042            4            0         4      100.0
BG043            4            0         4      100.0
BG044            4            0         4      100.0
BG045            4            0         4      100.0
BG046            4            0         4      100.0
BG047            4            0         4      100.0
BG048            4            0         4      100.0
BG049            4            0         4      100.0
BG050            4            0         4      100.0
BG051            4            0         4      100.0
BG052            4            0         4      100.0
BG053            4            0         4      100.0
BG055            4            0         4      100.0
BG057            4            0         4      100.0
BG058            4            0         4      100.0
BG059            4            0         4      100.0
BG061            4            0         4      100.0
BG063            4            0         4      100.0
BG065            4            0         4      100.0
BG067            4            0         4      100.0
BG069            4            0         4      100.0
BG071            4            0         4      100.0
BG073            4            0         4      100.0
BG075            4            0         4      100.0
BG077            4            0         4      100.0
BG079            4            0         4      100.0
BG081            4            0         4      100.0
BG083            4            0         4      100.0
BG086            4            0         4      100.0
BG087            4            0         4      100.0
BG089            4            0         4      100.0
BG091            4            0         4      100.0
BG093            4            0         4      100.0
BG095            4            0         4      100.0
BG096            4            0         4      100.0
BG097            4            0         4      100.0
BG098            4            0         4      100.0
BG099            4            0         4      100.0
BG100            4            0         4      100.0
BP022            4            0         4      100.0
BP024            4            0         4      100.0
BP026            4            0         4      100.0
BP027            4            0         4      100.0
BP029            4            0         4      100.0
BP032            4            0         4      100.0
BP036            4            0         4      100.0
BP066            4            0         4      100.0
BP068            4            0         4      100.0
BP069            4            0         4      100.0
BP070            4            0         4      100.0
BP071            4            0         4      100.0
BP072            4            0         4      100.0
BP073            4            0         4      100.0
BP074            4            0         4      100.0
BP075            4            0         4      100.0
BP076            4            0         4      100.0
BP078            4            0         4      100.0
BP079            4            0         4      100.0
BP080            4            0         4      100.0
BP081            4            0         4      100.0
BP082            4            0         4      100.0
BP083            4            0         4      100.0
BP084            4            0         4      100.0
BP085            4            0         4      100.0
BP086            4            0         4      100.0
BP088            4            0         4      100.0
BP090            4            0         4      100.0
BP092            4            0         4      100.0
BP094            4            0         4      100.0
BP096            4            0         4      100.0
BP098            4            0         4      100.0
BP099            4            0         4      100.0
BS002            4            0         4      100.0
BS006            4            0         4      100.0
BS017            4            0         4      100.0
BS018            4            0         4      100.0
BS024            4            0         4      100.0
BS026            4            0         4      100.0
BS027            4            0         4      100.0
BS028            4            0         4      100.0
BS029            4            0         4      100.0
BS030            4            0         4      100.0
BS031            4            0         4      100.0
BS032            4            0         4      100.0
BS033            4            0         4      100.0
BS038            4            0         4      100.0
BS042            4            0         4      100.0
BS043            4            0         4      100.0
BS046            4            0         4      100.0
BS049            4            0         4      100.0
BS050            4            0         4      100.0
BS051            4            0         4      100.0
BS052            4            0         4      100.0
BS054            4            0         4      100.0
BS055            4            0         4      100.0
BS056            4            0         4      100.0
BS057            4            0         4      100.0
BS058            4            0         4      100.0
BS059            4            0         4      100.0
BS060            4            0         4      100.0
BS061            4            0         4      100.0
BS062            4            0         4      100.0
BS070            4            0         4      100.0
BS071            4            0         4      100.0
BS072            4            0         4      100.0
BS073            4            0         4      100.0
BS074            4            0         4      100.0
BS075            4            0         4      100.0
BS077            4            0         4      100.0
BS079            4            0         4      100.0
BS081            4            0         4      100.0
BS083            4            0         4      100.0
BS085            4            0         4      100.0
BS088            4            0         4      100.0
BS090            4            0         4      100.0
BS095            4            0         4      100.0
BU001            4            0         4      100.0
BU002            4            0         4      100.0
BV001           12            0        12      100.0
BV010            4            0         4      100.0
BV013           12            0        12      100.0
BV035            4            0         4      100.0
BV037           12            0        12      100.0
BV041            4            0         4      100.0
BV062            4            0         4      100.0
BV063           12            0        12      100.0
BV067           12            0        12      100.0
BV070            4            0         4      100.0
BV076            4            0         4      100.0
BV080           12            0        12      100.0
BV081            4            0         4      100.0
BV083           12            0        12      100.0
BV085            4            0         4      100.0
BV105           12            0        12      100.0
BV130            4            0         4      100.0
BV133            4            0         4      100.0
BV135            4            0         4      100.0
BV136            4            0         4      100.0
BV137           12            0        12      100.0
BV138           12            0        12      100.0
BV139           12            0        12      100.0
BV140            4            0         4      100.0
BV141           12            0        12      100.0
BV142           12            0        12      100.0
BV143            4            0         4      100.0
BV144            4            0         4      100.0
BV145            4            0         4      100.0
BV146           12            0        12      100.0
BV147            4            0         4      100.0
BV148           12            0        12      100.0
BV149           12            0        12      100.0
BV150           12            0        12      100.0
BV151           12            0        12      100.0
BV152           12            0        12      100.0
BV153           11            0        11      100.0
BV154            4            0         4      100.0
BV155            4            0         4      100.0
BV156           12            0        12      100.0
BV157            4            0         4      100.0
BV158            4            0         4      100.0
BV159            4            0         4      100.0
BV160            4            0         4      100.0
BV161            4            0         4      100.0
BV162            4            0         4      100.0
CA002S           4            0         4      100.0
CA006S           4            0         4      100.0
CA007            4            0         4      100.0
CA009            4            0         4      100.0
IB001            4            0         4      100.0
IB003            4            0         4      100.0
IN001            4            0         4      100.0
IP001            4            0         4      100.0
IP003            4            0         4      100.0
IU001            4            0         4      100.0
JE001            4            0         4      100.0
JE002            4            0         4      100.0
JE003            4            0         4      100.0
JE004            4            0         4      100.0
JE005            4            0         4      100.0
JE006            4            0         4      100.0
JE007            4            0         4      100.0
JE008            4            0         4      100.0
JE009            4            0         4      100.0
JE010            4            0         4      100.0
JE011            4            0         4      100.0
JE012            4            0         4      100.0
JE013            4            0         4      100.0
JE014            4            0         4      100.0
JE015            4            0         4      100.0
JE016            3            0         3      100.0
JE017            4            0         4      100.0
JE018            4            0         4      100.0
JE019            4            0         4      100.0
JE020            4            0         4      100.0
JE021            4            0         4      100.0
JE022            4            0         4      100.0
JE023            4            0         4      100.0
JE024            4            0         4      100.0
JE025            4            0         4      100.0
JU001            4            0         4      100.0
JU003            4            0         4      100.0
MU001            4            0         4      100.0
MU002            4            0         4      100.0
MU003            4            0         4      100.0
MU005            4            0         4      100.0
MU006            4            0         4      100.0
MU007            4            0         4      100.0
MU008            4            0         4      100.0
MU009            4            0         4      100.0
MU011            4            0         4      100.0
MU013            4            0         4      100.0
MU014            4            0         4      100.0
PA001            4            0         4      100.0
PA002            4            0         4      100.0
PA003            4            0         4      100.0
PA004            4            0         4      100.0
PA005            4            0         4      100.0
PA007            4            0         4      100.0
PA009            4            0         4      100.0
PA010            4            0         4      100.0
PA011            4            0         4      100.0
PA013            4            0         4      100.0
PA015            4            0         4      100.0
PA017            4            0         4      100.0
PA019            4            0         4      100.0
PA020            4            0         4      100.0
PA021            4            0         4      100.0
PA022            4            0         4      100.0
PA023            4            0         4      100.0
PA024            4            0         4      100.0
PA025            4            0         4      100.0
PA026            4            0         4      100.0
PA028            4            0         4      100.0
PA029            4            0         4      100.0
PA031            4            0         4      100.0
PA032            4            0         4      100.0
PA034            4            0         4      100.0
PA036            4            0         4      100.0
PA040            4            0         4      100.0
PA042            4            0         4      100.0
PA044            4            0         4      100.0
PB001            4            0         4      100.0
PB002            4            0         4      100.0
PB003            4            0         4      100.0
PB005            4            0         4      100.0
PB007            4            0         4      100.0
PB009            4            0         4      100.0
PB011            4            0         4      100.0
PB013            4            0         4      100.0
PB015            4            0         4      100.0
PB017            4            0         4      100.0
PB019            4            0         4      100.0
PB021            4            0         4      100.0
PB022            4            0         4      100.0
PB023            4            0         4      100.0
PB025            4            0         4      100.0
PB027            4            0         4      100.0
PB029            4            0         4      100.0
PB031            4            0         4      100.0
PB033            4            0         4      100.0
PB034            4            0         4      100.0
PB035            4            0         4      100.0
PB036            4            0         4      100.0
PB037            4            0         4      100.0
PB038            4            0         4      100.0
PB039            4            0         4      100.0
PB040            4            0         4      100.0
PB041            4            0         4      100.0
PB042            4            0         4      100.0
PB043            4            0         4      100.0
PB044            4            0         4      100.0
PB045            4            0         4      100.0
PB046            4            0         4      100.0
PB047            4            0         4      100.0
PB048            4            0         4      100.0
PB049            4            0         4      100.0
PB050            4            0         4      100.0
PB051            4            0         4      100.0
PB052            4            0         4      100.0
PB053            4            0         4      100.0
PB054            4            0         4      100.0
PB055            4            0         4      100.0
PB056            3            0         3      100.0
PB057            4            0         4      100.0
PD001            3            0         3      100.0
PD002            4            0         4      100.0
PD003            4            0         4      100.0
PD004            4            0         4      100.0
PD005            4            0         4      100.0
PE001            4            0         4      100.0
PJ001            4            0         4      100.0
PJ003            4            0         4      100.0
PJ006            4            0         4      100.0
PJ009            4            0         4      100.0
PJ012            4            0         4      100.0
PJ015            4            0         4      100.0
PJ018            4            0         4      100.0
PJ021            4            0         4      100.0
PJ024            4            0         4      100.0
PT001            4            0         4      100.0
PT003            4            0         4      100.0
PT005            4            0         4      100.0
PT007            4            0         4      100.0
PT009            4            0         4      100.0
PT010            4            0         4      100.0
PT011            4            0         4      100.0
PT013            4            0         4      100.0
PTE001           4            0         4      100.0
PTE003           4            0         4      100.0
PTE005           4            0         4      100.0
PTE007           4            0         4      100.0
PTE009           4            0         4      100.0
PTE011           4            0         4      100.0
PTE013           4            0         4      100.0
PTE015           4            0         4      100.0
PTE017           4            0         4      100.0
PTE019           4            0         4      100.0
PTE021           4            0         4      100.0
PTE023           4            0         4      100.0
PTE025           4            0         4      100.0
PTE027           4            0         4      100.0
PTE029           4            0         4      100.0
PTE031           4            0         4      100.0
PTE033           4            0         4      100.0
PTE035           4            0         4      100.0
PTE037           4            0         4      100.0
PV005            4            0         4      100.0

In [ ]:
# Verificar ausência sistemática de valores por ano
(ausencia_por_ano == 100).sum()

pH in loco                        0
Turbidez                          0
Oxigênio dissolvido               0
Temperatura da água               0
Condutividade elétrica in loco    0
Demanda Bioquímica de Oxigênio    0
Fósforo total                     0
Nitrato                           0
Sólidos totais                    0
Nitrogênio amoniacal total        0
Coliformes termotolerantes        6
dtype: int64

In [ ]:
# Anos em que Coliformes termotolerantes
# apresentam 100% de valores ausentes

anos_100_missing = ausencia_por_ano[
    ausencia_por_ano["Coliformes termotolerantes"] == 100
].index.tolist()

anos_100_missing

[2014, 2015, 2016, 2017, 2018, 2019]

In [ ]:
# Quantidade de registros nos anos com 100% de ausência

registros_anos_100 = (
    df[df["ano"].isin(anos_100_missing)]
    .groupby("ano")
    .size()
    .reset_index(name="registros")
)

registros_anos_100

    ano  registros
0  2014       2637
1  2015       2626
2  2016       2542
3  2017       1734
4  2018       2745
5  2019       2786

Entre 2014 e 2019, o parâmetro Coliformes termotolerantes apresenta ausência completa na base analisada. São 15.070 registros distribuídos nesses seis anos, sem nenhuma observação preenchida para o parâmetro.

In [ ]:
# Cobertura de Coliformes termotolerantes por estação
# no período de 2014 a 2019

periodo_2014_2019 = df[
    df["ano"].between(2014, 2019)
]

cobertura_coliformes_estacao = (
    periodo_2014_2019
    .groupby("Estação")["Coliformes termotolerantes"]
    .agg(
        registros="size",
        preenchidos="count"
    )
)

cobertura_coliformes_estacao["ausentes"] = (
    cobertura_coliformes_estacao["registros"]
    - cobertura_coliformes_estacao["preenchidos"]
)

cobertura_coliformes_estacao["cobertura_%"] = (
    cobertura_coliformes_estacao["preenchidos"]
    / cobertura_coliformes_estacao["registros"]
    * 100
)

cobertura_coliformes_estacao.sort_values(
    "cobertura_%"
)

         registros  preenchidos  ausentes  cobertura_%
Estação
VG001           16            0        16          0.0
UR018            7            0         7          0.0
UR017           21            0        21          0.0
UR016           22            0        22          0.0
UR015           22            0        22          0.0
UR014           22            0        22          0.0
UR013           22            0        22          0.0
UR012           22            0        22          0.0
UR011           22            0        22          0.0
UR010           22            0        22          0.0
UR009           22            0        22          0.0
UR008           11            0        11          0.0
UR007           22            0        22          0.0
UR006           11            0        11          0.0
UR005           10            0        10          0.0
UR004           11            0        11          0.0
AV340           25            0        25          0.0
AV320           25            0        25          0.0
AV300           25            0        25          0.0
AV250           25            0        25          0.0
AV210           46            0        46          0.0
AV200           25            0        25          0.0
AV180E          15            0        15          0.0
AV160E          15            0        15          0.0
AV120           25            0        25          0.0
AV080           25            0        25          0.0
AV070           25            0        25          0.0
AV060           25            0        25          0.0
AV050           25            0        25          0.0
AV020           25            0        25          0.0
AV010           25            0        25          0.0
VG003           22            0        22          0.0
BG034           23            0        23          0.0
BG033           23            0        23          0.0
BG032           23            0        23          0.0
BG031           23            0        23          0.0
BG030           23            0        23          0.0
BG029           23            0        23          0.0
BG028           23            0        23          0.0
BG027           23            0        23          0.0
BG026           23            0        23          0.0
BG025           23            0        23          0.0
BG024           23            0        23          0.0
BG023           23            0        23          0.0
BG022           11            0        11          0.0
BG021           23            0        23          0.0
BG020           11            0        11          0.0
BG019           23            0        23          0.0
BG050           23            0        23          0.0
BG049           23            0        23          0.0
BG048           23            0        23          0.0
BG047           23            0        23          0.0
BG046           23            0        23          0.0
BG045           23            0        23          0.0
BG044           23            0        23          0.0
BG043           23            0        23          0.0
BG042           23            0        23          0.0
BG041           23            0        23          0.0
BG040           23            0        23          0.0
BG039           23            0        23          0.0
BG038           23            0        23          0.0
BG037           23            0        23          0.0
BG036           23            0        23          0.0
BG035           23            0        23          0.0
BG069           23            0        23          0.0
BG068           11            0        11          0.0
BG067           23            0        23          0.0
BG066            8            0         8          0.0
BG065           23            0        23          0.0
BG063           23            0        23          0.0
BG061           23            0        23          0.0
BG059           23            0        23          0.0
BG058           23            0        23          0.0
BG057           23            0        23          0.0
BG056           11            0        11          0.0
BG055           23            0        23          0.0
BG054           11            0        11          0.0
BG053           23            0        23          0.0
BG052           23            0        23          0.0
BG051           23            0        23          0.0
BG086           23            0        23          0.0
BG084            8            0         8          0.0
BG083           23            0        23          0.0
BG082            8            0         8          0.0
BG081           23            0        23          0.0
BG080            8            0         8          0.0
BG079           23            0        23          0.0
BG078           11            0        11          0.0
BG077           23            0        23          0.0
BG076            8            0         8          0.0
BG075           23            0        23          0.0
BG074           11            0        11          0.0
BG073           23            0        23          0.0
BG072           11            0        11          0.0
BG071           21            0        21          0.0
BG070            8            0         8          0.0
BP018           16            0        16          0.0
BP016           16            0        16          0.0
BP014           16            0        16          0.0
BG100           23            0        23          0.0
BG099           23            0        23          0.0
BG098           23            0        23          0.0
BG097           23            0        23          0.0
BG096           23            0        23          0.0
BG095           23            0        23          0.0
BG094           11            0        11          0.0
BG093           23            0        23          0.0
BG091           23            0        23          0.0
BG090           11            0        11          0.0
BG089           23            0        23          0.0
BG088           11            0        11          0.0
BG087           23            0        23          0.0
BP074           23            0        23          0.0
BP073           23            0        23          0.0
BP072           27            0        27          0.0
BP071           23            0        23          0.0
BP070           27            0        27          0.0
BP069           23            0        23          0.0
BP068           27            0        27          0.0
BP066           23            0        23          0.0
BP036           27            0        27          0.0
BP032           23            0        23          0.0
BP029           23            0        23          0.0
BP027           23            0        23          0.0
BP026           23            0        23          0.0
BP024           23            0        23          0.0
BP022           23            0        23          0.0
BP020           16            0        16          0.0
BP090           23            0        23          0.0
BP089            1            0         1          0.0
BP088           23            0        23          0.0
BP087            1            0         1          0.0
BP086           23            0        23          0.0
BP085           23            0        23          0.0
BP084           23            0        23          0.0
BP083           27            0        27          0.0
BP082           27            0        27          0.0
BP081           23            0        23          0.0
BP080           23            0        23          0.0
BP079           23            0        23          0.0
BP078           27            0        27          0.0
BP077            1            0         1          0.0
BP076           23            0        23          0.0
BP075           23            0        23          0.0
BS018           23            0        23          0.0
BS017           23            0        23          0.0
BS006           23            0        23          0.0
BS002           23            0        23          0.0
BPE9             5            0         5          0.0
BPE8             6            0         6          0.0
BPE7             6            0         6          0.0
BPE6             6            0         6          0.0
BPE3             6            0         6          0.0
BPE2             6            0         6          0.0
BP099           26            0        26          0.0
BP098           23            0        23          0.0
BP096           23            0        23          0.0
BP094           23            0        23          0.0
BP093            5            0         5          0.0
BP092           23            0        23          0.0
BS051           23            0        23          0.0
BS050           23            0        23          0.0
BS049           23            0        23          0.0
BS046           23            0        23          0.0
BS043           23            0        23          0.0
BS042           22            0        22          0.0
BS038           23            0        23          0.0
BS033           23            0        23          0.0
BS032           23            0        23          0.0
BS031           23            0        23          0.0
BS030           23            0        23          0.0
BS029           23            0        23          0.0
BS028           23            0        23          0.0
BS027           22            0        22          0.0
BS026           23            0        23          0.0
BS024           23            0        23          0.0
BS075           31            0        31          0.0
BS074           23            0        23          0.0
BS073           23            0        23          0.0
BS072           23            0        23          0.0
BS071           23            0        23          0.0
BS070           31            0        31          0.0
BS062           31            0        31          0.0
BS061           23            0        23          0.0
BS060           31            0        31          0.0
BS059           23            0        23          0.0
BS058           23            0        23          0.0
BS057           23            0        23          0.0
BS056           23            0        23          0.0
BS055           23            0        23          0.0
BS054           23            0        23          0.0
BS052           31            0        31          0.0
BV041           23            0        23          0.0
BV037           44            0        44          0.0
BV035           23            0        23          0.0
BV013           44            0        44          0.0
BV010           23            0        23          0.0
BV001           44            0        44          0.0
BU002           23            0        23          0.0
BU001           23            0        23          0.0
BS095           23            0        23          0.0
BS090           23            0        23          0.0
BS088           23            0        23          0.0
BS085           23            0        23          0.0
BS083           23            0        23          0.0
BS081           23            0        23          0.0
BS079           31            0        31          0.0
BS077           23            0        23          0.0
BV137           44            0        44          0.0
BV136           23            0        23          0.0
BV135           23            0        23          0.0
BV133           23            0        23          0.0
BV130           23            0        23          0.0
BV105           64            0        64          0.0
BV085           23            0        23          0.0
BV083           44            0        44          0.0
BV081           23            0        23          0.0
BV080           44            0        44          0.0
BV076           23            0        23          0.0
BV070           23            0        23          0.0
BV067           44            0        44          0.0
BV063           43            0        43          0.0
BV062           23            0        23          0.0
BV042            6            0         6          0.0
BV153           38            0        38          0.0
BV152           64            0        64          0.0
BV151           64            0        64          0.0
BV150           64            0        64          0.0
BV149           64            0        64          0.0
BV148           64            0        64          0.0
BV147           21            0        21          0.0
BV146           64            0        64          0.0
BV145           22            0        22          0.0
BV144           23            0        23          0.0
BV143           23            0        23          0.0
BV142           44            0        44          0.0
BV141           64            0        64          0.0
BV140           23            0        23          0.0
BV139           64            0        64          0.0
BV138           43            0        43          0.0
IN001           23            0        23          0.0
IB003           23            0        23          0.0
IB001           23            0        23          0.0
CA009           24            0        24          0.0
CA007           24            0        24          0.0
CA006S          24            0        24          0.0
CA002S          24            0        24          0.0
BV162           23            0        23          0.0
BV161           23            0        23          0.0
BV160           23            0        23          0.0
BV159           17            0        17          0.0
BV158           20            0        20          0.0
BV157           14            0        14          0.0
BV156           64            0        64          0.0
BV155           23            0        23          0.0
BV154           23            0        23          0.0
JE013           23            0        23          0.0
JE012           23            0        23          0.0
JE011           23            0        23          0.0
JE010           23            0        23          0.0
JE009           23            0        23          0.0
JE008           21            0        21          0.0
JE007           23            0        23          0.0
JE006           23            0        23          0.0
JE005           23            0        23          0.0
JE004           18            0        18          0.0
JE003           23            0        23          0.0
JE002           18            0        18          0.0
JE001           23            0        23          0.0
IU001           23            0        23          0.0
IP003           23            0        23          0.0
IP001           23            0        23          0.0
JE029           16            0        16          0.0
JE028           15            0        15          0.0
JE027           15            0        15          0.0
JE026           16            0        16          0.0
JE025           23            0        23          0.0
JE024           16            0        16          0.0
JE023           23            0        23          0.0
JE022           22            0        22          0.0
JE021           23            0        23          0.0
JE020           23            0        23          0.0
JE019           23            0        23          0.0
JE018           23            0        23          0.0
JE017           23            0        23          0.0
JE016           18            0        18          0.0
JE015           23            0        23          0.0
JE014           23            0        23          0.0
JE045            4            0         4          0.0
JE044            4            0         4          0.0
JE043            4            0         4          0.0
JE042            4            0         4          0.0
JE041            4            0         4          0.0
JE040            3            0         3          0.0
JE039            4            0         4          0.0
JE038            4            0         4          0.0
JE037            4            0         4          0.0
JE036            4            0         4          0.0
JE035            4            0         4          0.0
JE034            4            0         4          0.0
JE033            4            0         4          0.0
JE032            4            0         4          0.0
JE031            4            0         4          0.0
JE030            4            0         4          0.0
MU013           23            0        23          0.0
MU011           23            0        23          0.0
MU009           23            0        23          0.0
MU008           23            0        23          0.0
MU007           23            0        23          0.0
MU006           19            0        19          0.0
MU005           23            0        23          0.0
MU003           23            0        23          0.0
MU002           23            0        23          0.0
MU001           23            0        23          0.0
JU003           23            0        23          0.0
JU001           23            0        23          0.0
JE049            4            0         4          0.0
JE048            4            0         4          0.0
JE047            4            0         4          0.0
JE046            4            0         4          0.0
PA013           23            0        23          0.0
PA011           23            0        23          0.0
PA010           23            0        23          0.0
PA009           23            0        23          0.0
PA007           23            0        23          0.0
PA005           23            0        23          0.0
PA004           23            0        23          0.0
PA003           23            0        23          0.0
PA002           23            0        23          0.0
PA001           23            0        23          0.0
P5              12            0        12          0.0
P4              12            0        12          0.0
P3              12            0        12          0.0
P2              12            0        12          0.0
P1              12            0        12          0.0
MU014           23            0        23          0.0
PA036           23            0        23          0.0
PA034           16            0        16          0.0
PA032           23            0        23          0.0
PA031           23            0        23          0.0
PA029           23            0        23          0.0
PA028           23            0        23          0.0
PA026           23            0        23          0.0
PA025           23            0        23          0.0
PA024           23            0        23          0.0
PA023           23            0        23          0.0
PA022           23            0        23          0.0
PA021           23            0        23          0.0
PA020           23            0        23          0.0
PA019           23            0        23          0.0
PA017           23            0        23          0.0
PA015           23            0        23          0.0
PB019           22            0        22          0.0
PB017           22            0        22          0.0
PB016            8            0         8          0.0
PB015           22            0        22          0.0
PB013           22            0        22          0.0
PB011           22            0        22          0.0
PB009           22            0        22          0.0
PB007           22            0        22          0.0
PB005           22            0        22          0.0
PB004            8            0         8          0.0

Entre 2014 e 2019, nenhuma das estações apresenta registros preenchidos para Coliformes termotolerantes.

Portanto, notou-se uma ausência sistemática de registros desse parâmetro.

- Parâmetro: Coliformes termotolerantes
- Período: 2014–2019
- Estações afetadas: todas as estações presentes no período
- Cobertura no período: 0%
- Registros no período: 15.070
- Registros preenchidos: 0
- Registros ausentes: 15.070

In [ ]:
# Identificar períodos com ausência total para cada parâmetro

anos_100_missing_por_parametro = {}

for parametro in parametros:
    anos = ausencia_por_ano[
        ausencia_por_ano[parametro] == 100
    ].index.tolist()

    anos_100_missing_por_parametro[parametro] = anos

anos_100_missing_por_parametro

{'pH in loco': [],
 'Turbidez': [],
 'Oxigênio dissolvido': [],
 'Temperatura da água': [],
 'Condutividade elétrica in loco': [],
 'Demanda Bioquímica de Oxigênio': [],
 'Fósforo total': [],
 'Nitrato': [],
 'Sólidos totais': [],
 'Nitrogênio amoniacal total': [],
 'Coliformes termotolerantes': [2014, 2015, 2016, 2017, 2018, 2019]}

In [ ]:
# Queremos saber se as estações apresentam uma frequência de coleta relativamente consistente
# ao longo dos anos ou existem períodos com poucas/nenhuma observação
#
# Quantidade de amostras por estação e ano
amostras_estacao_ano = (
    df.groupby(["Estação", "ano"])
      .size()
      .reset_index(name="n_amostras")
)

amostras_estacao_ano.head(10)

  Estação   ano  n_amostras
0   AV005  2003           4
1   AV005  2004           4
2   AV005  2006           1
3   AV005  2007           4
4   AV005  2008           4
5   AV005  2009           4
6   AV005  2010           4
7   AV005  2011           4
8   AV005  2012           4
9   AV005  2013           3

In [ ]:
amostras_estacao_ano["n_amostras"].describe()

count    9883.000000
mean        4.008398
std         1.565164
min         1.000000
25%         4.000000
50%         4.000000
75%         4.000000
max        12.000000
Name: n_amostras, dtype: float64

In [ ]:
# Verificar quantas estações estão representadas nos registros
print("Número de estações:", amostras_estacao_ano["Estação"].nunique())

print("\nNúmero de anos:", amostras_estacao_ano["ano"].nunique())

print("\nDistribuição da quantidade de amostras por estação-ano:")
print(amostras_estacao_ano["n_amostras"].value_counts().sort_index())

Número de estações: 769

Número de anos: 23

Distribuição da quantidade de amostras por estação-ano:
n_amostras
1      202
2      629
3      746
4     7879
5       15
6       28
7       14
8       56
9       33
10      13
11      31
12     237
Name: count, dtype: int64

Das 9.883 combinações estação–ano, 7.879 têm exatamente 4 amostras, aproximadamente 79,7%. Portanto, 4 amostras por ano é o padrão predominante.
Isso sugere que a base possui uma estrutura temporal predominantemente regular, provavelmente compatível com uma frequência trimestral em grande parte das combinações, porém cabe realizar uma investigação mais detalhada.

In [ ]:
# Separar casos de baixa frequência
baixa_frequencia = (
    amostras_estacao_ano[
        amostras_estacao_ano["n_amostras"] <= 2
    ]
    .sort_values(["ano", "Estação"])
)

print("Combinações estação-ano com até 2 amostras:",
      len(baixa_frequencia))

baixa_frequencia.head(20)

Combinações estação-ano com até 2 amostras: 831

    Estação   ano  n_amostras
323   BG001  1997           1
349   BG003  1997           2
375   BG005  1997           2
401   BG007  1997           2
433   BG009  1997           2
467   BG011  1997           2
510   BG013  1997           2
553   BG015  1997           2
576   BG017  1997           2
602   BG019  1997           2
628   BG021  1997           2
654   BG023  1997           2
689   BG025  1997           2
724   BG027  1997           2
747   BG028  1997           2
770   BG029  1997           2
793   BG030  1997           2
816   BG031  1997           2
839   BG032  1997           2
862   BG033  1997           2

In [ ]:
# Separar casos de alta fequência
alta_frequencia = (
    amostras_estacao_ano[
        amostras_estacao_ano["n_amostras"] >= 8
    ]
    .sort_values(["ano", "Estação"])
)

print("Combinações estação-ano com 8 ou mais amostras:",
      len(alta_frequencia))

alta_frequencia.head(20)

Combinações estação-ano com 8 ou mais amostras: 370

     Estação   ano  n_amostras
126    AV090  2003          12
129    AV100  2003          12
132    AV120  2003          12
148    AV140  2003          12
151    AV150  2003          12
272    AV300  2003          12
289    AV320  2003          12
127    AV090  2004          12
130    AV100  2004          12
133    AV120  2004          12
149    AV140  2004          12
152    AV150  2004          12
273    AV300  2004          12
290    AV320  2004          12
292    AV320  2007          10
3133   BV035  2007          10
3188   BV062  2007          10
3211   BV063  2007          10
293    AV320  2008          12
3111   BV013  2008           8

In [ ]:
# Distribuição dos casos de baixa frequência por ano
baixa_por_ano = (
    baixa_frequencia
    .groupby("ano")
    .size()
    .reset_index(name="combinacoes_ate_2_amostras")
)

print(baixa_por_ano)

     ano  combinacoes_ate_2_amostras
0   1997                         183
1   1998                           5
2   1999                           3
3   2000                           2
4   2001                           2
5   2002                           9
6   2004                           1
7   2005                          37
8   2006                          54
9   2007                          56
10  2008                          55
11  2009                          30
12  2010                          57
13  2011                          44
14  2012                          38
15  2013                          22
16  2014                           5
17  2015                          17
18  2016                          30
19  2017                         157
20  2018                           9
21  2019                          15

In [ ]:
# Distribuição dos casos de alta frequência por ano
alta_por_ano = (
    alta_frequencia
    .groupby("ano")
    .size()
    .reset_index(name="combinacoes_8_ou_mais_amostras")
)

print(alta_por_ano)

     ano  combinacoes_8_ou_mais_amostras
0   2003                               7
1   2004                               7
2   2007                               4
3   2008                              19
4   2009                              22
5   2010                              22
6   2011                              21
7   2012                              21
8   2013                              37
9   2014                              40
10  2015                              46
11  2016                              46
12  2017                              15
13  2018                              30
14  2019                              33

Foram identificadas 831 combinações com até 2 registros e 370 com 8 ou mais registros. As diferenças de frequência apresentam concentração em determinados anos, especialmente nos primeiros anos da série e em 2017 para baixa frequência, e entre 2013–2016 para alta frequência.

Logo, a frequência de amostragem não é homogênea ao longo da série histórica. A maior parte das combinações estação–ano possui 4 observações, mas há períodos com menor e maior frequência, com concentração temporal desses desvios. Essas diferenças devem ser consideradas na interpretação temporal e comparativa, mas não foram classificadas como erros de qualidade sem evidência adicional.

In [ ]:
# ============================================
# TABELA DE ACHADOS DA AUDITORIA INICIAL
# ============================================

achados_auditoria = pd.DataFrame([
    {
        "id": "AQ-01",
        "categoria": "Estrutura",
        "verificacao": "Estrutura da base principal",
        "resultado": (
            "39.615 registros, 769 estações e período de "
            "02/07/1997 a 12/12/2019."
        ),
        "evidencia": (
            "df.shape; df['Estação'].nunique(); "
            "df['Data de Amostragem'].min()/max()"
        ),
        "severidade": "Informativo",
        "acao_recomendada": "Base apta para análise exploratória inicial."
    },

    {
        "id": "AQ-02",
        "categoria": "Duplicidade",
        "verificacao": "Duplicidade da chave estação-data-hora",
        "resultado": (
            "Não foram identificados registros duplicados pela combinação "
            "Estação + Data de Amostragem + Hora de Amostragem."
        ),
        "evidencia": "Registros duplicados pela chave = 0",
        "severidade": "OK",
        "acao_recomendada": "Manter a chave como controle de duplicidade."
    },

    {
        "id": "AQ-03",
        "categoria": "Completude",
        "verificacao": "Cobertura de Coliformes termotolerantes",
        "resultado": (
            "22.022 registros preenchidos de 39.615; cobertura de "
            "55,59% e ausência de dados em 44,41% dos registros."
        ),
        "evidencia": (
            "Contagem de valores não nulos e cálculo de cobertura "
            "do parâmetro."
        ),
        "severidade": "Atenção",
        "acao_recomendada": (
            "Preservar os dados ausentes e considerar a cobertura "
            "antes de análises que utilizem esse parâmetro."
        )
    },

    {
        "id": "AQ-04",
        "categoria": "Completude temporal",
        "verificacao": "Ausência sistemática de Coliformes termotolerantes",
        "resultado": (
            "Entre 2014 e 2019, foram identificados 15.070 registros "
            "sem observações de Coliformes termotolerantes. "
            "As estações presentes nesses anos apresentam 0% de cobertura."
        ),
        "evidencia": (
            "Análise por ano e por estação; anos com 100% de ausência: "
            "2014, 2015, 2016, 2017, 2018 e 2019."
        ),
        "severidade": "Atenção",
        "acao_recomendada": (
            "Não imputar automaticamente. Investigar a origem da ausência "
            "e bloquear interpretações de tendência contínua para esse parâmetro."
        )
    },

    {
        "id": "AQ-05",
        "categoria": "Consistência",
        "verificacao": "Valores de pH fora do intervalo [0, 14]",
        "resultado": "Nenhum valor fora do intervalo foi identificado.",
        "evidencia": "Teste de consistência aplicado à variável pH.",
        "severidade": "OK",
        "acao_recomendada": "Manter os valores; regra pode ser incorporada ao controle automatizado."
    },

    {
        "id": "AQ-06",
        "categoria": "Consistência",
        "verificacao": "Valores negativos de turbidez",
        "resultado": "Nenhum valor negativo foi identificado.",
        "evidencia": "Teste de consistência aplicado à variável Turbidez.",
        "severidade": "OK",
        "acao_recomendada": "Manter os valores; regra pode ser incorporada ao controle automatizado."
    },

    {
        "id": "AQ-07",
        "categoria": "Consistência",
        "verificacao": "Valores negativos de temperatura da água",
        "resultado": "Nenhum valor negativo foi identificado.",
        "evidencia": "Teste de consistência aplicado à variável Temperatura da água.",
        "severidade": "OK",
        "acao_recomendada": "Manter os valores; regra pode ser incorporada ao controle automatizado."
    },

    {
        "id": "AQ-08",
        "categoria": "Valores extremos",
        "verificacao": "Identificação de possíveis outliers pelo método do IQR",
        "resultado": (
            "Foram identificados valores extremos em diferentes parâmetros. "
            "A frequência de candidatos variou entre os parâmetros."
        ),
        "evidencia": (
            "Método do intervalo interquartil (IQR) aplicado aos 11 "
            "parâmetros selecionados."
        ),
        "severidade": "Atenção",
        "acao_recomendada": (
            "Tratar os outliers como candidatos à investigação, "
            "sem exclusão automática."
        )
    },

    {
        "id": "AQ-09",
        "categoria": "Cobertura amostral",
        "verificacao": "Número de amostras por estação e ano",
        "resultado": (
            "Foram identificadas 9.883 combinações estação-ano. "
            "Em 7.879 delas (aproximadamente 79,7%), houve exatamente "
            "4 amostras no ano."
        ),
        "evidencia": (
            "Distribuição da quantidade de registros por combinação "
            "Estação + Ano."
        ),
        "severidade": "Informativo",
        "acao_recomendada": (
            "Considerar a frequência amostral nas análises temporais "
            "e investigar combinações com frequência muito baixa ou alta."
        )
    },

    {
        "id": "AQ-10",
        "categoria": "Semântica dos dados",
        "verificacao": "Presença de sinais de medição",
        "resultado": (
            "A base possui colunas de sinal associadas aos parâmetros, "
            "incluindo operadores como '<' e '>'."
        ),
        "evidencia": (
            "Colunas 'Sinal ...' e distribuição dos valores das colunas "
            "de sinal."
        ),
        "severidade": "Atenção",
        "acao_recomendada": (
            "Preservar o sinal na transformação dos dados e não interpretar "
            "automaticamente valores censurados como medições exatas."
        )
    }
])

# Visualizar a tabela
display(achados_auditoria)

,id,categoria,verificacao,resultado,evidencia,severidade,acao_recomendada
0,AQ-01,Estrutura,Estrutura da base principal,"39.615 registros, 769 estações e período de 02...",df.shape; df['Estação'].nunique(); df['Data de...,Informativo,Base apta para análise exploratória inicial.
1,AQ-02,Duplicidade,Duplicidade da chave estação-data-hora,Não foram identificados registros duplicados p...,Registros duplicados pela chave = 0,OK,Manter a chave como controle de duplicidade.
2,AQ-03,Completude,Cobertura de Coliformes termotolerantes,22.022 registros preenchidos de 39.615; cobert...,Contagem de valores não nulos e cálculo de cob...,Atenção,Preservar os dados ausentes e considerar a cob...
3,AQ-04,Completude temporal,Ausência sistemática de Coliformes termotolera...,"Entre 2014 e 2019, foram identificados 15.070 ...",Análise por ano e por estação; anos com 100% d...,Atenção,Não imputar automaticamente. Investigar a orig...
4,AQ-05,Consistência,"Valores de pH fora do intervalo [0, 14]",Nenhum valor fora do intervalo foi identificado.,Teste de consistência aplicado à variável pH.,OK,Manter os valores; regra pode ser incorporada ...
5,AQ-06,Consistência,Valores negativos de turbidez,Nenhum valor negativo foi identificado.,Teste de consistência aplicado à variável Turb...,OK,Manter os valores; regra pode ser incorporada ...
6,AQ-07,Consistência,Valores negativos de temperatura da água,Nenhum valor negativo foi identificado.,Teste de consistência aplicado à variável Temp...,OK,Manter os valores; regra pode ser incorporada ...
7,AQ-08,Valores extremos,Identificação de possíveis outliers pelo métod...,Foram identificados valores extremos em difere...,Método do intervalo interquartil (IQR) aplicad...,Atenção,Tratar os outliers como candidatos à investiga...
8,AQ-09,Cobertura amostral,Número de amostras por estação e ano,Foram identificadas 9.883 combinações estação-...,Distribuição da quantidade de registros por co...,Informativo,Considerar a frequência amostral nas análises ...
9,AQ-10,Semântica dos dados,Presença de sinais de medição,A base possui colunas de sinal associadas aos ...,Colunas 'Sinal ...' e distribuição dos valores...,Atenção,Preservar o sinal na transformação dos dados e...

In [ ]:
# Salvar tabela como csv
achados_auditoria.to_csv(
    "achados_auditoria.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo: achados_auditoria.csv")

Arquivo salvo: achados_auditoria.csv

In [ ]:
# Queremos transformar os achados em regras que o sistema poderá
# executar novamente em outra base compatível.
#
# ============================================
# REGRAS DE QUALIDADE DOS DADOS
# ============================================

regras_qualidade = pd.DataFrame([
    {
        "id": "CQ-01",
        "categoria": "Estrutura",
        "regra": "Verificar presença das colunas obrigatórias",
        "criterio": (
            "A base deve conter Estação, Data de Amostragem "
            "e Hora de Amostragem."
        ),
        "tipo": "Bloqueante",
        "acao_falha": (
            "Interromper a análise e informar quais colunas "
            "obrigatórias estão ausentes."
        )
    },

    {
        "id": "CQ-02",
        "categoria": "Estrutura",
        "regra": "Verificar duplicidade da observação",
        "criterio": (
            "Não deve haver duplicidade na combinação "
            "Estação + Data de Amostragem + Hora de Amostragem."
        ),
        "tipo": "Atenção",
        "acao_falha": (
            "Sinalizar registros duplicados para investigação; "
            "não excluir automaticamente."
        )
    },

    {
        "id": "CQ-03",
        "categoria": "Completude",
        "regra": "Calcular cobertura dos parâmetros",
        "criterio": (
            "Calcular quantidade e percentual de valores "
            "preenchidos e ausentes para cada parâmetro."
        ),
        "tipo": "Informativa",
        "acao_falha": (
            "Registrar a cobertura e sinalizar parâmetros "
            "com baixa disponibilidade de dados."
        )
    },

    {
        "id": "CQ-04",
        "categoria": "Completude temporal",
        "regra": "Detectar ausência sistemática de dados",
        "criterio": (
            "Identificar parâmetros com períodos em que a "
            "ausência de dados seja sistemática por ano "
            "ou outro intervalo temporal."
        ),
        "tipo": "Atenção",
        "acao_falha": (
            "Sinalizar o período afetado e impedir interpretações "
            "de continuidade temporal sem evidência suficiente."
        )
    },

    {
        "id": "CQ-05",
        "categoria": "Consistência",
        "regra": "Verificar regras físicas previamente declaradas",
        "criterio": (
            "Aplicar somente restrições de domínio explicitamente "
            "definidas para cada variável."
        ),
        "tipo": "Atenção",
        "acao_falha": (
            "Sinalizar valores incompatíveis com a regra, "
            "sem exclusão automática."
        )
    },

    {
        "id": "CQ-06",
        "categoria": "Valores extremos",
        "regra": "Identificar possíveis outliers",
        "criterio": (
            "Utilizar o intervalo interquartil (IQR) como método "
            "de triagem de valores extremos."
        ),
        "tipo": "Diagnóstica",
        "acao_falha": (
            "Sinalizar observações extremas para investigação. "
            "Não considerar o outlier como erro automaticamente."
        )
    },

    {
        "id": "CQ-07",
        "categoria": "Cobertura amostral",
        "regra": "Verificar frequência de amostragem",
        "criterio": (
            "Calcular o número de observações por estação e "
            "período temporal."
        ),
        "tipo": "Diagnóstica",
        "acao_falha": (
            "Sinalizar estações/períodos com frequência "
            "amostral muito baixa ou discrepante."
        )
    },

    {
        "id": "CQ-08",
        "categoria": "Semântica",
        "regra": "Preservar sinais associados às medições",
        "criterio": (
            "Manter os campos de sinal, como '<' e '>', "
            "associados aos respectivos valores."
        ),
        "tipo": "Bloqueante",
        "acao_falha": (
            "Impedir a transformação que descarte o sinal "
            "ou altere sua interpretação."
        )
    },

    {
        "id": "CQ-09",
        "categoria": "Dados ausentes",
        "regra": "Não imputar valores automaticamente",
        "criterio": (
            "Valores ausentes devem permanecer ausentes durante "
            "a auditoria, salvo quando uma estratégia de imputação "
            "for explicitamente definida para uma análise."
        ),
        "tipo": "Bloqueante",
        "acao_falha": (
            "Manter NaN e registrar a ausência no relatório."
        )
    }
])

display(regras_qualidade)

,id,categoria,regra,criterio,tipo,acao_falha
0,CQ-01,Estrutura,Verificar presença das colunas obrigatórias,"A base deve conter Estação, Data de Amostragem...",Bloqueante,Interromper a análise e informar quais colunas...
1,CQ-02,Estrutura,Verificar duplicidade da observação,Não deve haver duplicidade na combinação Estaç...,Atenção,Sinalizar registros duplicados para investigaç...
2,CQ-03,Completude,Calcular cobertura dos parâmetros,Calcular quantidade e percentual de valores pr...,Informativa,Registrar a cobertura e sinalizar parâmetros c...
3,CQ-04,Completude temporal,Detectar ausência sistemática de dados,Identificar parâmetros com períodos em que a a...,Atenção,Sinalizar o período afetado e impedir interpre...
4,CQ-05,Consistência,Verificar regras físicas previamente declaradas,Aplicar somente restrições de domínio explicit...,Atenção,"Sinalizar valores incompatíveis com a regra, s..."
5,CQ-06,Valores extremos,Identificar possíveis outliers,Utilizar o intervalo interquartil (IQR) como m...,Diagnóstica,Sinalizar observações extremas para investigaç...
6,CQ-07,Cobertura amostral,Verificar frequência de amostragem,Calcular o número de observações por estação e...,Diagnóstica,Sinalizar estações/períodos com frequência amo...
7,CQ-08,Semântica,Preservar sinais associados às medições,"Manter os campos de sinal, como '<' e '>', ass...",Bloqueante,Impedir a transformação que descarte o sinal o...
8,CQ-09,Dados ausentes,Não imputar valores automaticamente,Valores ausentes devem permanecer ausentes dur...,Bloqueante,Manter NaN e registrar a ausência no relatório.

In [ ]:
print(f"Total de regras: {len(regras_qualidade)}")

print("\nRegras por categoria:")
display(regras_qualidade["categoria"].value_counts())

print("\nRegras por tipo:")
display(regras_qualidade["tipo"].value_counts())

Total de regras: 9

Regras por categoria:

categoria
Estrutura              2
Completude             1
Completude temporal    1
Consistência           1
Valores extremos       1
Cobertura amostral     1
Semântica              1
Dados ausentes         1
Name: count, dtype: int64

Regras por tipo:

tipo
Bloqueante     3
Atenção        3
Diagnóstica    2
Informativa    1
Name: count, dtype: int64

In [ ]:
# Salvar como cvs
regras_qualidade.to_csv(
    "regras_qualidade.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo: regras_qualidade.csv")

Arquivo salvo: regras_qualidade.csv

In [ ]:
# Criar a função do quality_checker
# ============================================
# QUALITY CHECKER - VERSÃO 1
# Regras CQ-01, CQ-02 e CQ-03
# ============================================

def executar_quality_checker(df):

    resultados = []

    # ----------------------------------------
    # CQ-01 - Estrutura
    # ----------------------------------------

    colunas_obrigatorias = [
        "Estação",
        "Data de Amostragem",
        "Hora de Amostragem"
    ]

    colunas_ausentes = [
        coluna for coluna in colunas_obrigatorias
        if coluna not in df.columns
    ]

    if len(colunas_ausentes) == 0:
        resultados.append({
            "regra": "CQ-01",
            "status": "OK",
            "resultado": "Todas as colunas obrigatórias estão presentes.",
            "evidencia": ", ".join(colunas_obrigatorias)
        })
    else:
        resultados.append({
            "regra": "CQ-01",
            "status": "BLOQUEADO",
            "resultado": "Existem colunas obrigatórias ausentes.",
            "evidencia": ", ".join(colunas_ausentes)
        })


    # ----------------------------------------
    # CQ-02 - Duplicidade
    # ----------------------------------------

    chave = [
        "Estação",
        "Data de Amostragem",
        "Hora de Amostragem"
    ]

    duplicados = df.duplicated(
        subset=chave,
        keep=False
    ).sum()

    if duplicados == 0:
        resultados.append({
            "regra": "CQ-02",
            "status": "OK",
            "resultado": "Nenhuma duplicidade identificada.",
            "evidencia": "0 registros duplicados pela chave estação-data-hora."
        })
    else:
        resultados.append({
            "regra": "CQ-02",
            "status": "ATENÇÃO",
            "resultado": f"{duplicados} registros envolvidos em duplicidades.",
            "evidencia": "Duplicidade detectada na chave estação-data-hora."
        })


    # ----------------------------------------
    # CQ-03 - Completude
    # ----------------------------------------

    parametros = [
        "pH in loco",
        "Turbidez",
        "Oxigênio dissolvido",
        "Temperatura da água",
        "Condutividade elétrica in loco",
        "Demanda Bioquímica de Oxigênio",
        "Fósforo total",
        "Nitrato",
        "Sólidos totais",
        "Nitrogênio amoniacal total",
        "Coliformes termotolerantes"
    ]

    for parametro in parametros:

        if parametro not in df.columns:
            resultados.append({
                "regra": "CQ-03",
                "status": "ATENÇÃO",
                "resultado": f"Parâmetro ausente: {parametro}",
                "evidencia": "Coluna não encontrada na base."
            })
            continue

        total = len(df)
        preenchidos = df[parametro].notna().sum()
        ausentes = df[parametro].isna().sum()
        cobertura = (preenchidos / total) * 100

        resultados.append({
            "regra": "CQ-03",
            "status": "OK",
            "resultado": (
                f"{parametro}: {cobertura:.2f}% de cobertura."
            ),
            "evidencia": (
                f"Preenchidos={preenchidos}; "
                f"ausentes={ausentes}; "
                f"total={total}."
            )
        })


    return pd.DataFrame(resultados)

In [ ]:
resultado_quality_checker = executar_quality_checker(df)

display(resultado_quality_checker)

,regra,status,resultado,evidencia
0,CQ-01,OK,Todas as colunas obrigatórias estão presentes.,"Estação, Data de Amostragem, Hora de Amostragem"
1,CQ-02,OK,Nenhuma duplicidade identificada.,0 registros duplicados pela chave estação-data...
2,CQ-03,OK,pH in loco: 99.77% de cobertura.,Preenchidos=39525; ausentes=90; total=39615.
3,CQ-03,OK,Turbidez: 99.85% de cobertura.,Preenchidos=39556; ausentes=59; total=39615.
4,CQ-03,OK,Oxigênio dissolvido: 99.88% de cobertura.,Preenchidos=39567; ausentes=48; total=39615.
5,CQ-03,OK,Temperatura da água: 99.88% de cobertura.,Preenchidos=39566; ausentes=49; total=39615.
6,CQ-03,OK,Condutividade elétrica in loco: 99.61% de cobe...,Preenchidos=39461; ausentes=154; total=39615.
7,CQ-03,OK,Demanda Bioquímica de Oxigênio: 99.22% de cobe...,Preenchidos=39305; ausentes=310; total=39615.
8,CQ-03,OK,Fósforo total: 99.17% de cobertura.,Preenchidos=39288; ausentes=327; total=39615.
9,CQ-03,OK,Nitrato: 99.14% de cobertura.,Preenchidos=39276; ausentes=339; total=39615.
10,CQ-03,OK,Sólidos totais: 98.37% de cobertura.,Preenchidos=38968; ausentes=647; total=39615.
11,CQ-03,OK,Nitrogênio amoniacal total: 96.87% de cobertura.,Preenchidos=38376; ausentes=1239; total=39615.
12,CQ-03,OK,Coliformes termotolerantes: 55.59% de cobertura.,Preenchidos=22022; ausentes=17593; total=39615.

In [ ]:
# Criar cópia para testar o funcionamento do checker
df_teste = df.copy()

In [ ]:
# Adiciona uma cópia do primeiro registro
df_teste = pd.concat(
    [df_teste, df_teste.iloc[[0]]],
    ignore_index=True
)

print("Registros originais:", len(df))
print("Registros após inserção do teste:", len(df_teste))

Registros originais: 39615
Registros após inserção do teste: 39616

In [ ]:
resultado_teste = executar_quality_checker(df_teste)

display(
    resultado_teste[
        resultado_teste["regra"] == "CQ-02"
    ]
)

,regra,status,resultado,evidencia
1,CQ-02,ATENÇÃO,2 registros envolvidos em duplicidades.,Duplicidade detectada na chave estação-data-hora.

In [ ]:
# ============================================
# CQ-04 - AUSÊNCIA SISTEMÁTICA DE DADOS
# ============================================

def verificar_ausencia_temporal(df, parametros):

    resultados = []

    # Criar ano a partir da data de amostragem
    dados = df.copy()
    dados["ano"] = pd.to_datetime(
        dados["Data de Amostragem"],
        errors="coerce"
    ).dt.year

    for parametro in parametros:

        if parametro not in dados.columns:
            resultados.append({
                "regra": "CQ-04",
                "parametro": parametro,
                "ano": None,
                "registros": None,
                "preenchidos": None,
                "ausentes": None,
                "cobertura_pct": None,
                "status": "ATENÇÃO",
                "evidencia": "Parâmetro não encontrado na base."
            })
            continue

        # Agrupamento por ano
        for ano, grupo in dados.groupby("ano"):

            total = len(grupo)
            preenchidos = grupo[parametro].notna().sum()
            ausentes = grupo[parametro].isna().sum()

            if total > 0:
                cobertura = (preenchidos / total) * 100
            else:
                cobertura = 0

            # Classificação da ausência
            if preenchidos == 0:
                status = "AUSÊNCIA TOTAL"
            else:
                status = "DADOS DISPONÍVEIS"

            resultados.append({
                "regra": "CQ-04",
                "parametro": parametro,
                "ano": int(ano),
                "registros": total,
                "preenchidos": preenchidos,
                "ausentes": ausentes,
                "cobertura_pct": round(cobertura, 2),
                "status": status,
                "evidencia": (
                    f"{ausentes} ausentes de {total} registros."
                )
            })

    return pd.DataFrame(resultados)

In [ ]:
parametros = [
    "pH in loco",
    "Turbidez",
    "Oxigênio dissolvido",
    "Temperatura da água",
    "Condutividade elétrica in loco",
    "Demanda Bioquímica de Oxigênio",
    "Fósforo total",
    "Nitrato",
    "Sólidos totais",
    "Nitrogênio amoniacal total",
    "Coliformes termotolerantes"
]

resultado_cq04 = verificar_ausencia_temporal(
    df,
    parametros
)

display(resultado_cq04.head(20))

,regra,parametro,ano,registros,preenchidos,ausentes,cobertura_pct,status,evidencia
0,CQ-04,pH in loco,1997,421,421,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 421 registros.
1,CQ-04,pH in loco,1998,745,745,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 745 registros.
2,CQ-04,pH in loco,1999,795,795,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 795 registros.
3,CQ-04,pH in loco,2000,959,959,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 959 registros.
4,CQ-04,pH in loco,2001,962,962,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 962 registros.
5,CQ-04,pH in loco,2002,971,971,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 971 registros.
6,CQ-04,pH in loco,2003,1159,1159,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 1159 registros.
7,CQ-04,pH in loco,2004,1161,1161,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 1161 registros.
8,CQ-04,pH in loco,2005,1156,1156,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 1156 registros.
9,CQ-04,pH in loco,2006,1322,1322,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 1322 registros.
10,CQ-04,pH in loco,2007,1534,1534,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 1534 registros.
11,CQ-04,pH in loco,2008,1841,1841,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 1841 registros.
12,CQ-04,pH in loco,2009,2055,2055,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 2055 registros.
13,CQ-04,pH in loco,2010,2183,2183,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 2183 registros.
14,CQ-04,pH in loco,2011,2309,2308,1,99.96,DADOS DISPONÍVEIS,1 ausentes de 2309 registros.
15,CQ-04,pH in loco,2012,2386,2386,0,100.00,DADOS DISPONÍVEIS,0 ausentes de 2386 registros.
16,CQ-04,pH in loco,2013,2586,2583,3,99.88,DADOS DISPONÍVEIS,3 ausentes de 2586 registros.
17,CQ-04,pH in loco,2014,2637,2632,5,99.81,DADOS DISPONÍVEIS,5 ausentes de 2637 registros.
18,CQ-04,pH in loco,2015,2626,2597,29,98.90,DADOS DISPONÍVEIS,29 ausentes de 2626 registros.
19,CQ-04,pH in loco,2016,2542,2538,4,99.84,DADOS DISPONÍVEIS,4 ausentes de 2542 registros.

In [ ]:
# Verificar ausências totais
ausencias_totais = resultado_cq04[
    resultado_cq04["status"] == "AUSÊNCIA TOTAL"
].copy()

display(ausencias_totais)

,regra,parametro,ano,registros,preenchidos,ausentes,cobertura_pct,status,evidencia
247,CQ-04,Coliformes termotolerantes,2014,2637,0,2637,0.0,AUSÊNCIA TOTAL,2637 ausentes de 2637 registros.
248,CQ-04,Coliformes termotolerantes,2015,2626,0,2626,0.0,AUSÊNCIA TOTAL,2626 ausentes de 2626 registros.
249,CQ-04,Coliformes termotolerantes,2016,2542,0,2542,0.0,AUSÊNCIA TOTAL,2542 ausentes de 2542 registros.
250,CQ-04,Coliformes termotolerantes,2017,1734,0,1734,0.0,AUSÊNCIA TOTAL,1734 ausentes de 1734 registros.
251,CQ-04,Coliformes termotolerantes,2018,2745,0,2745,0.0,AUSÊNCIA TOTAL,2745 ausentes de 2745 registros.
252,CQ-04,Coliformes termotolerantes,2019,2786,0,2786,0.0,AUSÊNCIA TOTAL,2786 ausentes de 2786 registros.

In [ ]:
# Criar cópia para testar o funcionamento do checker
df_teste_cq04 = df.copy()

In [ ]:
import numpy as np
# Apagar deliberadamente os dados de Nitrato em 2010
df_teste_cq04.loc[
    df_teste_cq04["Data de Amostragem"].dt.year == 2010,
    "Nitrato"
] = np.nan

In [ ]:
resultado_teste_cq04 = verificar_ausencia_temporal(
    df_teste_cq04,
    parametros
)

In [ ]:
display(
    resultado_teste_cq04[
        (
            (resultado_teste_cq04["parametro"] == "Nitrato") &
            (resultado_teste_cq04["ano"] == 2010)
        )
    ]
)

,regra,parametro,ano,registros,preenchidos,ausentes,cobertura_pct,status,evidencia
174,CQ-04,Nitrato,2010,2183,0,2183,0.0,AUSÊNCIA TOTAL,2183 ausentes de 2183 registros.

In [ ]:
# ============================================
# CQ-05 - CONSISTÊNCIA FÍSICA
# ============================================

def verificar_consistencia_fisica(df):

    resultados = []

    # ----------------------------------------
    # Regra 1 - pH
    # ----------------------------------------

    parametro = "pH in loco"

    if parametro in df.columns:

        invalidos = df[
            (df[parametro] < 0) |
            (df[parametro] > 14)
        ]

        quantidade = len(invalidos)

        if quantidade == 0:
            status = "OK"
            resultado = "Nenhum valor de pH fora do intervalo [0, 14]."
        else:
            status = "ATENÇÃO"
            resultado = (
                f"{quantidade} valores de pH fora do intervalo [0, 14]."
            )

        resultados.append({
            "regra": "CQ-05",
            "parametro": parametro,
            "criterio": "0 <= pH <= 14",
            "quantidade_invalidos": quantidade,
            "status": status,
            "resultado": resultado
        })

    # ----------------------------------------
    # Regra 2 - Turbidez
    # ----------------------------------------

    parametro = "Turbidez"

    if parametro in df.columns:

        invalidos = df[
            df[parametro] < 0
        ]

        quantidade = len(invalidos)

        if quantidade == 0:
            status = "OK"
            resultado = "Nenhum valor negativo de turbidez."
        else:
            status = "ATENÇÃO"
            resultado = (
                f"{quantidade} valores negativos de turbidez."
            )

        resultados.append({
            "regra": "CQ-05",
            "parametro": parametro,
            "criterio": "Turbidez >= 0",
            "quantidade_invalidos": quantidade,
            "status": status,
            "resultado": resultado
        })

    # ----------------------------------------
    # Regra 3 - Temperatura da água
    # ----------------------------------------

    parametro = "Temperatura da água"

    if parametro in df.columns:

        invalidos = df[
            df[parametro] < 0
        ]

        quantidade = len(invalidos)

        if quantidade == 0:
            status = "OK"
            resultado = (
                "Nenhum valor negativo de temperatura da água."
            )
        else:
            status = "ATENÇÃO"
            resultado = (
                f"{quantidade} valores negativos de temperatura da água."
            )

        resultados.append({
            "regra": "CQ-05",
            "parametro": parametro,
            "criterio": "Temperatura >= 0",
            "quantidade_invalidos": quantidade,
            "status": status,
            "resultado": resultado
        })

    return pd.DataFrame(resultados)

In [ ]:
# Executar na base original
resultado_cq05 = verificar_consistencia_fisica(df)

display(resultado_cq05)

,regra,parametro,criterio,quantidade_invalidos,status,resultado
0,CQ-05,pH in loco,0 <= pH <= 14,0,OK,"Nenhum valor de pH fora do intervalo [0, 14]."
1,CQ-05,Turbidez,Turbidez >= 0,0,OK,Nenhum valor negativo de turbidez.
2,CQ-05,Temperatura da água,Temperatura >= 0,0,OK,Nenhum valor negativo de temperatura da água.

In [ ]:
# Criar cópia para verificar funcionamento da função
df_teste_cq05 = df.copy()

In [ ]:
# Introduzir valores artificialmente inválidos

df_teste_cq05.loc[0, "pH in loco"] = 20
df_teste_cq05.loc[1, "Turbidez"] = -10
df_teste_cq05.loc[2, "Temperatura da água"] = -5

In [ ]:
# Teste
resultado_teste_cq05 = verificar_consistencia_fisica(
    df_teste_cq05
)

display(resultado_teste_cq05)

,regra,parametro,criterio,quantidade_invalidos,status,resultado
0,CQ-05,pH in loco,0 <= pH <= 14,1,ATENÇÃO,"1 valores de pH fora do intervalo [0, 14]."
1,CQ-05,Turbidez,Turbidez >= 0,1,ATENÇÃO,1 valores negativos de turbidez.
2,CQ-05,Temperatura da água,Temperatura >= 0,1,ATENÇÃO,1 valores negativos de temperatura da água.

In [ ]:
# ============================================
# CQ-06 - IDENTIFICAÇÃO DE VALORES EXTREMOS
# ============================================

def verificar_outliers_iqr(df, parametros):

    resultados = []

    for parametro in parametros:

        if parametro not in df.columns:
            resultados.append({
                "regra": "CQ-06",
                "parametro": parametro,
                "q1": None,
                "q3": None,
                "limite_inferior": None,
                "limite_superior": None,
                "total_validos": 0,
                "outliers": 0,
                "percentual_outliers": None,
                "status": "ATENÇÃO",
                "resultado": "Parâmetro não encontrado."
            })
            continue

        serie = df[parametro].dropna()

        if len(serie) == 0:
            resultados.append({
                "regra": "CQ-06",
                "parametro": parametro,
                "q1": None,
                "q3": None,
                "limite_inferior": None,
                "limite_superior": None,
                "total_validos": 0,
                "outliers": 0,
                "percentual_outliers": None,
                "status": "ATENÇÃO",
                "resultado": "Não existem valores válidos para análise."
            })
            continue

        # Quartis
        q1 = serie.quantile(0.25)
        q3 = serie.quantile(0.75)

        # Intervalo interquartil
        iqr = q3 - q1

        # Limites
        limite_inferior = q1 - 1.5 * iqr
        limite_superior = q3 + 1.5 * iqr

        # Identificação dos candidatos
        outliers = serie[
            (serie < limite_inferior) |
            (serie > limite_superior)
        ]

        total_validos = len(serie)
        quantidade_outliers = len(outliers)
        percentual = (
            quantidade_outliers / total_validos
        ) * 100

        if quantidade_outliers == 0:
            status = "OK"
        else:
            status = "ATENÇÃO"

        resultados.append({
            "regra": "CQ-06",
            "parametro": parametro,
            "q1": round(q1, 4),
            "q3": round(q3, 4),
            "limite_inferior": round(limite_inferior, 4),
            "limite_superior": round(limite_superior, 4),
            "total_validos": total_validos,
            "outliers": quantidade_outliers,
            "percentual_outliers": round(percentual, 2),
            "status": status,
            "resultado": (
                f"{quantidade_outliers} possíveis outliers "
                f"({percentual:.2f}% dos valores válidos)."
            )
        })

    return pd.DataFrame(resultados)

In [ ]:
# Executar na base original
resultado_cq06 = verificar_outliers_iqr(
    df,
    parametros
)

display(resultado_cq06)

,regra,parametro,q1,q3,limite_inferior,limite_superior,total_validos,outliers,percentual_outliers,status,resultado
0,CQ-06,pH in loco,6.50,7.30,5.300,8.500,39525,625,1.58,ATENÇÃO,625 possíveis outliers (1.58% dos valores váli...
1,CQ-06,Turbidez,8.11,50.50,-55.475,114.085,39556,5318,13.44,ATENÇÃO,5318 possíveis outliers (13.44% dos valores vá...
2,CQ-06,Oxigênio dissolvido,6.30,7.80,4.050,10.050,39567,4066,10.28,ATENÇÃO,4066 possíveis outliers (10.28% dos valores vá...
3,CQ-06,Temperatura da água,21.70,26.30,14.800,33.200,39566,281,0.71,ATENÇÃO,281 possíveis outliers (0.71% dos valores váli...
4,CQ-06,Condutividade elétrica in loco,38.70,134.00,-104.250,276.950,39461,4360,11.05,ATENÇÃO,4360 possíveis outliers (11.05% dos valores vá...
5,CQ-06,Demanda Bioquímica de Oxigênio,2.00,2.80,0.800,4.000,39305,7280,18.52,ATENÇÃO,7280 possíveis outliers (18.52% dos valores vá...
6,CQ-06,Fósforo total,0.02,0.12,-0.130,0.270,39288,4442,11.31,ATENÇÃO,4442 possíveis outliers (11.31% dos valores vá...
7,CQ-06,Nitrato,0.11,0.68,-0.745,1.535,39276,3189,8.12,ATENÇÃO,3189 possíveis outliers (8.12% dos valores vál...
8,CQ-06,Sólidos totais,57.00,180.00,-127.500,364.500,38968,3097,7.95,ATENÇÃO,3097 possíveis outliers (7.95% dos valores vál...
9,CQ-06,Nitrogênio amoniacal total,0.10,0.30,-0.200,0.600,38376,6327,16.49,ATENÇÃO,6327 possíveis outliers (16.49% dos valores vá...
10,CQ-06,Coliformes termotolerantes,220.00,13000.00,-18950.000,32170.000,22022,3219,14.62,ATENÇÃO,3219 possíveis outliers (14.62% dos valores vá...

In [ ]:
# Parâmetros com maior quantidade de candidatos
resultado_cq06.sort_values(
    "percentual_outliers",
    ascending=False
)[
    [
        "parametro",
        "total_validos",
        "outliers",
        "percentual_outliers",
        "limite_inferior",
        "limite_superior",
        "status"
    ]
]

,parametro,total_validos,outliers,percentual_outliers,limite_inferior,limite_superior,status
5,Demanda Bioquímica de Oxigênio,39305,7280,18.52,0.800,4.000,ATENÇÃO
9,Nitrogênio amoniacal total,38376,6327,16.49,-0.200,0.600,ATENÇÃO
10,Coliformes termotolerantes,22022,3219,14.62,-18950.000,32170.000,ATENÇÃO
1,Turbidez,39556,5318,13.44,-55.475,114.085,ATENÇÃO
6,Fósforo total,39288,4442,11.31,-0.130,0.270,ATENÇÃO
4,Condutividade elétrica in loco,39461,4360,11.05,-104.250,276.950,ATENÇÃO
2,Oxigênio dissolvido,39567,4066,10.28,4.050,10.050,ATENÇÃO
7,Nitrato,39276,3189,8.12,-0.745,1.535,ATENÇÃO
8,Sólidos totais,38968,3097,7.95,-127.500,364.500,ATENÇÃO
0,pH in loco,39525,625,1.58,5.300,8.500,ATENÇÃO
3,Temperatura da água,39566,281,0.71,14.800,33.200,ATENÇÃO

In [ ]:
# Criar uma cópia para testar o funcionamento da função
df_teste_cq06 = df.copy()

In [ ]:
# Inserir um valor artificialmente extremo de pH
df_teste_cq06.loc[0, "pH in loco"] = 1000

In [ ]:
# Teste
resultado_teste_cq06 = verificar_outliers_iqr(
    df_teste_cq06,
    parametros
)

display(
    resultado_teste_cq06[
        resultado_teste_cq06["parametro"] == "pH in loco"
    ]
)

,regra,parametro,q1,q3,limite_inferior,limite_superior,total_validos,outliers,percentual_outliers,status,resultado
0,CQ-06,pH in loco,6.5,7.3,5.3,8.5,39525,626,1.58,ATENÇÃO,626 possíveis outliers (1.58% dos valores váli...

In [ ]:
# ============================================
# CQ-07 - FREQUÊNCIA DE AMOSTRAGEM
# ============================================

def verificar_frequencia_amostragem(df):

    dados = df.copy()

    # Criar ano
    dados["ano"] = pd.to_datetime(
        dados["Data de Amostragem"],
        errors="coerce"
    ).dt.year

    # Frequência por estação e ano
    frequencia = (
        dados
        .groupby(["Estação", "ano"])
        .size()
        .reset_index(name="n_amostras")
    )

    # Classificação operacional
    def classificar_frequencia(n):
        if n <= 2:
            return "BAIXA"
        elif n >= 8:
            return "ALTA"
        else:
            return "ESPERADA"

    frequencia["classificacao"] = (
        frequencia["n_amostras"]
        .apply(classificar_frequencia)
    )

    return frequencia

In [ ]:
# Executar na base original
resultado_cq07 = verificar_frequencia_amostragem(df)

display(resultado_cq07.head(20))

   Estação   ano  n_amostras classificacao
0    AV005  2003           4      ESPERADA
1    AV005  2004           4      ESPERADA
2    AV005  2006           1         BAIXA
3    AV005  2007           4      ESPERADA
4    AV005  2008           4      ESPERADA
5    AV005  2009           4      ESPERADA
6    AV005  2010           4      ESPERADA
7    AV005  2011           4      ESPERADA
8    AV005  2012           4      ESPERADA
9    AV005  2013           3      ESPERADA
10   AV007  2006           1         BAIXA
11   AV007  2007           4      ESPERADA
12   AV007  2008           4      ESPERADA
13   AV007  2009           4      ESPERADA
14   AV007  2010           4      ESPERADA
15   AV007  2011           4      ESPERADA
16   AV007  2012           4      ESPERADA
17   AV007  2013           4      ESPERADA
18   AV007  2014           4      ESPERADA
19   AV007  2015           4      ESPERADA

In [ ]:
print("Total de combinações estação-ano:", len(resultado_cq07))

Total de combinações estação-ano: 9883

In [ ]:
display(
    resultado_cq07["classificacao"]
    .value_counts()
)

classificacao
ESPERADA    8682
BAIXA        831
ALTA         370
Name: count, dtype: int64

Importante: As faixas BAIXA (1–2), ESPERADA (3–7) e ALTA (≥8) são classificações operacionais para triagem da auditoria, e não critérios de adequação do programa de monitoramento.

In [ ]:
# Combinações com extamente 4 amostras
quantidade_exatamente_4 = (
    resultado_cq07["n_amostras"] == 4
).sum()

percentual_exatamente_4 = (
    quantidade_exatamente_4 /
    len(resultado_cq07)
) * 100

print(
    f"Combinações com exatamente 4 amostras: "
    f"{quantidade_exatamente_4}"
)

print(
    f"Percentual: "
    f"{percentual_exatamente_4:.2f}%"
)

Combinações com exatamente 4 amostras: 7879
Percentual: 79.72%

In [ ]:
# ============================================
# CQ-08 - PRESERVAÇÃO DOS SINAIS DE MEDIÇÃO
# ============================================

def verificar_sinais_medicao(df):

    resultados = []

    # Identificar colunas de sinal
    colunas_sinal = [
        coluna for coluna in df.columns
        if coluna.startswith("Sinal ")
    ]

    if len(colunas_sinal) == 0:
        return pd.DataFrame([{
            "regra": "CQ-08",
            "parametro": None,
            "coluna_sinal": None,
            "sinais_encontrados": None,
            "total_com_sinal": 0,
            "sinal_sem_valor": 0,
            "status": "ATENÇÃO",
            "resultado": "Nenhuma coluna de sinal foi identificada."
        }])

    for coluna_sinal in colunas_sinal:

        # Nome do parâmetro correspondente
        parametro = coluna_sinal.replace("Sinal ", "", 1)

        # Se não existir a coluna correspondente ao valor
        if parametro not in df.columns:
            resultados.append({
                "regra": "CQ-08",
                "parametro": parametro,
                "coluna_sinal": coluna_sinal,
                "sinais_encontrados": None,
                "total_com_sinal": 0,
                "sinal_sem_valor": None,
                "status": "ATENÇÃO",
                "resultado": (
                    "Coluna de sinal sem coluna de valor correspondente."
                )
            })
            continue

        serie_sinal = df[coluna_sinal]
        serie_valor = df[parametro]

        # Valores de sinal presentes
        sinais_validos = (
            serie_sinal
            .dropna()
            .astype(str)
            .str.strip()
        )

        # Remover strings vazias
        sinais_validos = sinais_validos[
            sinais_validos != ""
        ]

        # Frequência dos sinais
        distribuicao = sinais_validos.value_counts()

        # Quantidade de sinais preenchidos
        total_com_sinal = len(sinais_validos)

        # Sinal preenchido, mas valor ausente
        sinal_sem_valor = (
            serie_sinal.notna() &
            serie_sinal.astype(str).str.strip().ne("") &
            serie_valor.isna()
        ).sum()

        # Montar representação da distribuição
        if len(distribuicao) > 0:
            sinais_encontrados = "; ".join(
                [
                    f"{sinal}: {quantidade}"
                    for sinal, quantidade
                    in distribuicao.items()
                ]
            )
        else:
            sinais_encontrados = "Nenhum sinal preenchido"

        if sinal_sem_valor > 0:
            status = "ATENÇÃO"
            resultado = (
                f"{sinal_sem_valor} registros possuem sinal "
                f"sem valor correspondente."
            )
        else:
            status = "OK"
            resultado = (
                "Sinais preservados e associados às respectivas "
                "colunas de valor."
            )

        resultados.append({
            "regra": "CQ-08",
            "parametro": parametro,
            "coluna_sinal": coluna_sinal,
            "sinais_encontrados": sinais_encontrados,
            "total_com_sinal": total_com_sinal,
            "sinal_sem_valor": sinal_sem_valor,
            "status": status,
            "resultado": resultado
        })

    return pd.DataFrame(resultados)

In [ ]:
# Executar na base original
resultado_cq08 = verificar_sinais_medicao(df)

print(
    f"Colunas de sinal analisadas: "
    f"{len(resultado_cq08)}"
)

display(resultado_cq08.head(20))

Colunas de sinal analisadas: 96

,regra,parametro,coluna_sinal,sinais_encontrados,total_com_sinal,sinal_sem_valor,status,resultado
0,CQ-08,"2,4,6 Triclorofenol","Sinal 2,4,6 Triclorofenol",<: 143,143,0,OK,Sinais preservados e associados às respectivas...
1,CQ-08,Alcalinidade de bicarbonato,Sinal Alcalinidade de bicarbonato,<: 14,14,0,OK,Sinais preservados e associados às respectivas...
2,CQ-08,Alcalinidade total,Sinal Alcalinidade total,<: 14,14,0,OK,Sinais preservados e associados às respectivas...
3,CQ-08,Aldrin + Dieldrin,Sinal Aldrin + Dieldrin,<: 142,142,0,OK,Sinais preservados e associados às respectivas...
4,CQ-08,Alumínio dissolvido,Sinal Alumínio dissolvido,<: 9184,9184,0,OK,Sinais preservados e associados às respectivas...
5,CQ-08,Alumínio total,Sinal Alumínio total,<: 38,38,0,OK,Sinais preservados e associados às respectivas...
6,CQ-08,Arsênio Dissolvido,Sinal Arsênio Dissolvido,<: 536,536,0,OK,Sinais preservados e associados às respectivas...
7,CQ-08,Arsênio total,Sinal Arsênio total,<: 17044,17044,0,OK,Sinais preservados e associados às respectivas...
8,CQ-08,Atrazina,Sinal Atrazina,<: 146,146,0,OK,Sinais preservados e associados às respectivas...
9,CQ-08,Bário total,Sinal Bário total,<: 1679,1679,0,OK,Sinais preservados e associados às respectivas...
10,CQ-08,Boro dissolvido,Sinal Boro dissolvido,<: 3739,3739,0,OK,Sinais preservados e associados às respectivas...
11,CQ-08,Boro total,Sinal Boro total,<: 6486,6486,0,OK,Sinais preservados e associados às respectivas...
12,CQ-08,Cádmio total,Sinal Cádmio total,<: 27900,27900,0,OK,Sinais preservados e associados às respectivas...
13,CQ-08,Cálcio total,Sinal Cálcio total,<: 39,39,0,OK,Sinais preservados e associados às respectivas...
14,CQ-08,Chumbo total,Sinal Chumbo total,<: 25972,25972,0,OK,Sinais preservados e associados às respectivas...
15,CQ-08,Cianeto Livre,Sinal Cianeto Livre,<: 11268,11268,0,OK,Sinais preservados e associados às respectivas...
16,CQ-08,Cianeto total,Sinal Cianeto total,<: 7647,7647,0,OK,Sinais preservados e associados às respectivas...
17,CQ-08,Clordano - cis + trans,Sinal Clordano - cis + trans,<: 147,147,0,OK,Sinais preservados e associados às respectivas...
18,CQ-08,Cloreto total,Sinal Cloreto total,<: 2117,2117,0,OK,Sinais preservados e associados às respectivas...
19,CQ-08,Clorofila a,Sinal Clorofila a,<: 4573,4573,0,OK,Sinais preservados e associados às respectivas...

In [ ]:
# Consolidar os sinais encontrados

sinais_observados = []

for coluna in colunas_sinal:

    if coluna in df.columns:

        sinais = (
            df[coluna]
            .dropna()
            .astype(str)
            .str.strip()
        )

        sinais = sinais[sinais != ""]

        for sinal, quantidade in sinais.value_counts().items():
            sinais_observados.append({
                "coluna_sinal": coluna,
                "sinal": sinal,
                "quantidade": quantidade
            })

sinais_observados = pd.DataFrame(sinais_observados)

display(
    sinais_observados
    .sort_values("quantidade", ascending=False)
    .head(30)
)

                            coluna_sinal sinal  quantidade
12                    Sinal Cádmio total     <       27900
31  Sinal Demanda Bioquímica de Oxigênio     <       26008
14                    Sinal Chumbo total     <       25972
20                Sinal Cobre dissolvido     <       24074
44                   Sinal Fenóis totais     <       23712
28                     Sinal Cromo total     <       22950
55                  Sinal Mercúrio total     <       22682
75         Sinal Substâncias tensoativas     <       20439
59                    Sinal Níquel total     <       19693
77                         Sinal Sulfeto     <       18579
7                    Sinal Arsênio total     <       17044
62      Sinal Nitrogênio amoniacal total     <       15469
64                  Sinal Óleos e graxas     <       15125
81                     Sinal Zinco total     <       13504
15                   Sinal Cianeto Livre     <       11268
71                   Sinal Selênio total     <       10692
4              Sinal Alumínio dissolvido     <        9184
24               Sinal Coliformes totais     >        9091
76                   Sinal Sulfato total     <        8987
16                   Sinal Cianeto total     <        7647
11                      Sinal Boro total     <        6486
49                   Sinal Fósforo total     <        6229
27               Sinal Cromo hexavalente     <        5274
19                     Sinal Clorofila a     <        4573
21                     Sinal Cobre total     <        4407
32     Sinal Demanda Química de Oxigênio     <        4145
10                 Sinal Boro dissolvido     <        3739
29                Sinal Cromo trivalente     <        3536
26                  Sinal Cor verdadeira     <        2746
63             Sinal Nitrogênio orgânico     <        2723

In [ ]:
# Criar uma cópia para testar o funcionamento da função
df_teste_cq08 = df.copy()

In [ ]:
# Encontrar uma coluna de sinal com pelo menos um registro disponível
coluna_teste_sinal = colunas_sinal[0]

parametro_teste = coluna_teste_sinal.replace(
    "Sinal ", "", 1
)

print("Coluna de sinal:", coluna_teste_sinal)
print("Parâmetro:", parametro_teste)

Coluna de sinal: Sinal 2,4,6 Triclorofenol
Parâmetro: 2,4,6 Triclorofenol

In [ ]:
# Encontrar uma linha onde o valor esteja preenchido
linha_teste = df_teste_cq08[
    df_teste_cq08[parametro_teste].notna()
].index[0]

# Criar artificialmente um sinal sem valor correspondente
df_teste_cq08.loc[
    linha_teste,
    parametro_teste
] = np.nan

df_teste_cq08.loc[
    linha_teste,
    coluna_teste_sinal
] = "<"

print("Linha alterada para teste:", linha_teste)

Linha alterada para teste: 1848

In [ ]:
# Teste
resultado_teste_cq08 = verificar_sinais_medicao(
    df_teste_cq08
)

display(
    resultado_teste_cq08[
        resultado_teste_cq08["coluna_sinal"] == coluna_teste_sinal
    ]
)

,regra,parametro,coluna_sinal,sinais_encontrados,total_com_sinal,sinal_sem_valor,status,resultado
0,CQ-08,"2,4,6 Triclorofenol","Sinal 2,4,6 Triclorofenol",<: 143,143,1,ATENÇÃO,1 registros possuem sinal sem valor correspond...

In [ ]:
# ============================================
# CQ-09 - PRESERVAÇÃO DE DADOS AUSENTES
# ============================================

def verificar_preservacao_ausentes(df_original, df_auditoria):

    resultados = []

    # Verificar se as estruturas possuem as mesmas colunas
    colunas_originais = set(df_original.columns)
    colunas_auditoria = set(df_auditoria.columns)

    colunas_faltantes = colunas_originais - colunas_auditoria

    if len(colunas_faltantes) > 0:
        return pd.DataFrame([{
            "regra": "CQ-09",
            "status": "BLOQUEADO",
            "colunas_analisadas": 0,
            "colunas_com_alteracao": None,
            "resultado": (
                "A estrutura da base auditada não possui todas "
                "as colunas da base original."
            ),
            "evidencia": ", ".join(colunas_faltantes)
        }])

    # Considerar somente as colunas comuns
    colunas = [
        coluna for coluna in df_original.columns
        if coluna in df_auditoria.columns
    ]

    alteracoes = []

    for coluna in colunas:

        nulos_original = df_original[coluna].isna().sum()
        nulos_auditoria = df_auditoria[coluna].isna().sum()

        if nulos_original != nulos_auditoria:
            alteracoes.append({
                "coluna": coluna,
                "nulos_original": nulos_original,
                "nulos_auditoria": nulos_auditoria,
                "diferenca": nulos_auditoria - nulos_original
            })

    if len(alteracoes) == 0:
        status = "OK"
        resultado = (
            "A quantidade de valores ausentes foi preservada "
            "em todas as colunas."
        )
    else:
        status = "ATENÇÃO"
        resultado = (
            f"{len(alteracoes)} colunas apresentaram alteração "
            "na quantidade de valores ausentes."
        )

    resultados.append({
        "regra": "CQ-09",
        "status": status,
        "colunas_analisadas": len(colunas),
        "colunas_com_alteracao": len(alteracoes),
        "resultado": resultado,
        "evidencia": alteracoes
    })

    return pd.DataFrame(resultados)

In [ ]:
# Executar na base original
resultado_cq09 = verificar_preservacao_ausentes(
    df,
    df.copy()
)

display(resultado_cq09)

,regra,status,colunas_analisadas,colunas_com_alteracao,resultado,evidencia
0,CQ-09,OK,196,0,A quantidade de valores ausentes foi preservad...,[]

In [ ]:
# Criar cópia para testar funcionamento da função
df_teste_cq09 = df.copy()

In [ ]:
# Encontrar uma linha com valor ausente
linha_teste = df_teste_cq09[
    df_teste_cq09["Coliformes termotolerantes"].isna()
].index[0]

# Preencher artificialmente o valor ausente
df_teste_cq09.loc[
    linha_teste,
    "Coliformes termotolerantes"
] = 999

print("Linha modificada:", linha_teste)

Linha modificada: 24

In [ ]:
# Teste
resultado_teste_cq09 = verificar_preservacao_ausentes(
    df,
    df_teste_cq09
)

display(resultado_teste_cq09)

,regra,status,colunas_analisadas,colunas_com_alteracao,resultado,evidencia
0,CQ-09,ATENÇÃO,196,1,1 colunas apresentaram alteração na quantidade...,"[{'coluna': 'Coliformes termotolerantes', 'nul..."

In [ ]:
# ============================================
# CQ-10 - RASTREABILIDADE
# ============================================

from datetime import datetime


def registrar_execucao_quality_checker(
    resultados,
    nome_execucao="quality_checker"
):

    timestamp = datetime.now().isoformat(
        timespec="seconds"
    )

    registros = []

    for _, linha in resultados.iterrows():

        registros.append({
            "execucao": nome_execucao,
            "timestamp": timestamp,
            "regra": linha.get("regra"),
            "status": linha.get("status"),
            "resultado": linha.get("resultado"),
            "evidencia": (
                linha.get("evidencia")
                if "evidencia" in linha.index
                else None
            )
        })

    return pd.DataFrame(registros)

In [ ]:
# Testar com CQ-04
log_cq04 = registrar_execucao_quality_checker(
    resultado_cq04,
    nome_execucao="teste_CQ04"
)

display(log_cq04.head(20))

,execucao,timestamp,regra,status,resultado,evidencia
0,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 421 registros.
1,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 745 registros.
2,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 795 registros.
3,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 959 registros.
4,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 962 registros.
5,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 971 registros.
6,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 1159 registros.
7,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 1161 registros.
8,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 1156 registros.
9,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 1322 registros.
10,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 1534 registros.
11,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 1841 registros.
12,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 2055 registros.
13,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 2183 registros.
14,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,1 ausentes de 2309 registros.
15,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,0 ausentes de 2386 registros.
16,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,3 ausentes de 2586 registros.
17,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,5 ausentes de 2637 registros.
18,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,29 ausentes de 2626 registros.
19,teste_CQ04,2026-09-17T18:54:01,CQ-04,DADOS DISPONÍVEIS,None,4 ausentes de 2542 registros.

In [ ]:
# Criar resumo geral
def resumir_resultado(regra, resultado, coluna_status="status"):

    if resultado is None or len(resultado) == 0:
        return {
            "regra": regra,
            "status": "NÃO EXECUTADO",
            "resultado": "Nenhum resultado produzido.",
            "evidencia": None
        }

    contagem_status = (
        resultado[coluna_status]
        .value_counts()
        .to_dict()
    )

    # Determinar status geral
    if "BLOQUEADO" in contagem_status:
        status_geral = "BLOQUEADO"
    elif "ATENÇÃO" in contagem_status:
        status_geral = "ATENÇÃO"
    elif "AUSÊNCIA TOTAL" in contagem_status:
        status_geral = "ATENÇÃO"
    else:
        status_geral = "OK"

    return {
        "regra": regra,
        "status": status_geral,
        "resultado": str(contagem_status),
        "evidencia": (
            f"{len(resultado)} registros de resultado produzidos."
        )
    }

In [ ]:
resumo_quality_checker = pd.DataFrame([

    resumir_resultado(
        "CQ-04",
        resultado_cq04
    ),

    resumir_resultado(
        "CQ-05",
        resultado_cq05
    ),

    resumir_resultado(
        "CQ-06",
        resultado_cq06
    ),

    {
        "regra": "CQ-07",
        "status": "OK",
        "resultado": (
            f"{len(resultado_cq07)} combinações estação-ano analisadas."
        ),
        "evidencia": (
            "Distribuição das classificações de frequência "
            "por estação e ano."
        )
    },

    {
        "regra": "CQ-08",
        "status": (
            "ATENÇÃO"
            if (resultado_cq08["status"] == "ATENÇÃO").any()
            else "OK"
        ),
        "resultado": (
            f"{len(resultado_cq08)} colunas de sinal analisadas."
        ),
        "evidencia": (
            "Distribuição dos sinais e verificação de "
            "sinais sem valor correspondente."
        )
    },

    {
        "regra": "CQ-09",
        "status": resultado_cq09.iloc[0]["status"],
        "resultado": resultado_cq09.iloc[0]["resultado"],
        "evidencia": str(
            resultado_cq09.iloc[0]["evidencia"]
        )
    }
])

display(resumo_quality_checker)

,regra,status,resultado,evidencia
0,CQ-04,ATENÇÃO,"{'DADOS DISPONÍVEIS': 247, 'AUSÊNCIA TOTAL': 6}",253 registros de resultado produzidos.
1,CQ-05,OK,{'OK': 3},3 registros de resultado produzidos.
2,CQ-06,ATENÇÃO,{'ATENÇÃO': 11},11 registros de resultado produzidos.
3,CQ-07,OK,9883 combinações estação-ano analisadas.,Distribuição das classificações de frequência ...
4,CQ-08,OK,96 colunas de sinal analisadas.,Distribuição dos sinais e verificação de sinai...
5,CQ-09,OK,A quantidade de valores ausentes foi preservad...,[]

In [ ]:
# Incorporar CQ-01, CQ-02 e CQ-03
resumo_inicial = pd.DataFrame([
    {
        "regra": "CQ-01",
        "status": resultado_quality_checker[
            resultado_quality_checker["regra"] == "CQ-01"
        ].iloc[0]["status"],
        "resultado": resultado_quality_checker[
            resultado_quality_checker["regra"] == "CQ-01"
        ].iloc[0]["resultado"],
        "evidencia": resultado_quality_checker[
            resultado_quality_checker["regra"] == "CQ-01"
        ].iloc[0]["evidencia"]
    },

    {
        "regra": "CQ-02",
        "status": resultado_quality_checker[
            resultado_quality_checker["regra"] == "CQ-02"
        ].iloc[0]["status"],
        "resultado": resultado_quality_checker[
            resultado_quality_checker["regra"] == "CQ-02"
        ].iloc[0]["resultado"],
        "evidencia": resultado_quality_checker[
            resultado_quality_checker["regra"] == "CQ-02"
        ].iloc[0]["evidencia"]
    },

    {
        "regra": "CQ-03",
        "status": "OK",
        "resultado": (
            "Cobertura calculada para os parâmetros selecionados."
        ),
        "evidencia": (
            "Resultado detalhado disponível em resultado_quality_checker."
        )
    }
])

In [ ]:
# Log final
log_final = pd.concat(
    [
        resumo_inicial,
        resumo_quality_checker
    ],
    ignore_index=True
)

log_final["timestamp"] = datetime.now().isoformat(
    timespec="seconds"
)

display(log_final)

,regra,status,resultado,evidencia,timestamp
0,CQ-01,OK,Todas as colunas obrigatórias estão presentes.,"Estação, Data de Amostragem, Hora de Amostragem",2026-09-17T19:00:47
1,CQ-02,OK,Nenhuma duplicidade identificada.,0 registros duplicados pela chave estação-data...,2026-09-17T19:00:47
2,CQ-03,OK,Cobertura calculada para os parâmetros selecio...,Resultado detalhado disponível em resultado_qu...,2026-09-17T19:00:47
3,CQ-04,ATENÇÃO,"{'DADOS DISPONÍVEIS': 247, 'AUSÊNCIA TOTAL': 6}",253 registros de resultado produzidos.,2026-09-17T19:00:47
4,CQ-05,OK,{'OK': 3},3 registros de resultado produzidos.,2026-09-17T19:00:47
5,CQ-06,ATENÇÃO,{'ATENÇÃO': 11},11 registros de resultado produzidos.,2026-09-17T19:00:47
6,CQ-07,OK,9883 combinações estação-ano analisadas.,Distribuição das classificações de frequência ...,2026-09-17T19:00:47
7,CQ-08,OK,96 colunas de sinal analisadas.,Distribuição dos sinais e verificação de sinai...,2026-09-17T19:00:47
8,CQ-09,OK,A quantidade de valores ausentes foi preservad...,[],2026-09-17T19:00:47

In [ ]:
# Salvar log como csv
log_final.to_csv(
    "quality_checker_log.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Log salvo como quality_checker_log.csv")

Log salvo como quality_checker_log.csv

In [ ]:
# ============================================
# PRÉ-VALIDAÇÃO DA ESTRUTURA WIDE
# ============================================

# Colunas identificadoras da observação
colunas_id = [
    "Estação",
    "Data de Amostragem",
    "Hora de Amostragem"
]

# Identifica as colunas de parâmetros (excluindo identificadores,
# coluna de ano e colunas de sinal)
colunas_parametros = [
    c for c in df.columns
    if c not in colunas_id
    and c != "ano"
    and not c.startswith("Sinal ")
]

# Para cada parâmetro, verifica se existe sua coluna de sinal
pares_parametros = []

for parametro in colunas_parametros:
    coluna_sinal = f"Sinal {parametro}"

    pares_parametros.append({
        "parametro": parametro,
        "coluna_valor": parametro,
        "coluna_sinal": coluna_sinal,
        "sinal_existe": coluna_sinal in df.columns
    })

pares_parametros = pd.DataFrame(pares_parametros)

# Resumo da estrutura
print(f"Total de colunas de parâmetros identificadas: {len(pares_parametros)}")
print(
    f"Parâmetros com coluna de sinal correspondente: "
    f"{pares_parametros['sinal_existe'].sum()}"
)
print(
    f"Parâmetros sem coluna de sinal correspondente: "
    f"{(~pares_parametros['sinal_existe']).sum()}"
)

print("\nColunas de parâmetros sem sinal correspondente:")
display(
    pares_parametros.loc[
        ~pares_parametros["sinal_existe"],
        ["parametro", "coluna_sinal"]
    ]
)

print("\nPrimeiros pares identificados:")
display(pares_parametros.head(15))

Total de colunas de parâmetros identificadas: 96
Parâmetros com coluna de sinal correspondente: 96
Parâmetros sem coluna de sinal correspondente: 0

Colunas de parâmetros sem sinal correspondente:

Empty DataFrame
Columns: [parametro, coluna_sinal]
Index: []

Primeiros pares identificados:

,parametro,coluna_valor,coluna_sinal,sinal_existe
0,"2,4,6 Triclorofenol","2,4,6 Triclorofenol","Sinal 2,4,6 Triclorofenol",True
1,Alcalinidade de bicarbonato,Alcalinidade de bicarbonato,Sinal Alcalinidade de bicarbonato,True
2,Alcalinidade total,Alcalinidade total,Sinal Alcalinidade total,True
3,Aldrin + Dieldrin,Aldrin + Dieldrin,Sinal Aldrin + Dieldrin,True
4,Alumínio dissolvido,Alumínio dissolvido,Sinal Alumínio dissolvido,True
5,Alumínio total,Alumínio total,Sinal Alumínio total,True
6,Arsênio Dissolvido,Arsênio Dissolvido,Sinal Arsênio Dissolvido,True
7,Arsênio total,Arsênio total,Sinal Arsênio total,True
8,Atrazina,Atrazina,Sinal Atrazina,True
9,Bário total,Bário total,Sinal Bário total,True
10,Boro dissolvido,Boro dissolvido,Sinal Boro dissolvido,True
11,Boro total,Boro total,Sinal Boro total,True
12,Cádmio total,Cádmio total,Sinal Cádmio total,True
13,Cálcio total,Cálcio total,Sinal Cálcio total,True
14,Chumbo total,Chumbo total,Sinal Chumbo total,True

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
# Na base original (wide), cada parâmetro ocupa uma coluna. Então, criaremos uma
# base transformada (long), na qual cada parâmetro vira uma linha. Isso facilita
# as análises posteriores, pois nos permite agrupar, comparar, calcular estatísticas
# e criar gráficos por parâmetro, estação ou período usando a mesma estrutura.
# ============================================
# TRANSFORMAÇÃO WIDE → LONG
# ============================================

registros_long = []

for _, linha in df.iterrows():

    # Dados identificadores da observação
    dados_base = {
        "Estação": linha["Estação"],
        "Data de Amostragem": linha["Data de Amostragem"],
        "Hora de Amostragem": linha["Hora de Amostragem"],
    }

    for parametro in colunas_parametros:

        coluna_sinal = f"Sinal {parametro}"

        registros_long.append({
            **dados_base,
            "parametro": parametro,
            "valor": linha[parametro],
            "sinal": linha[coluna_sinal]
        })

df_long = pd.DataFrame(registros_long)

print("Dimensões da base original:", df.shape)
print("Dimensões da base long:", df_long.shape)

print("\nColunas da base long:")
print(df_long.columns.tolist())

print("\nPrimeiras observações:")
display(df_long.head(10))

Dimensões da base original: (39615, 196)
Dimensões da base long: (3803040, 6)

Colunas da base long:
['Estação', 'Data de Amostragem', 'Hora de Amostragem', 'parametro', 'valor', 'sinal']

Primeiras observações:

,Estação,Data de Amostragem,Hora de Amostragem,parametro,valor,sinal
0,AV005,2003-01-13,11:20:00,"2,4,6 Triclorofenol",NaN,NaN
1,AV005,2003-01-13,11:20:00,Alcalinidade de bicarbonato,NaN,NaN
2,AV005,2003-01-13,11:20:00,Alcalinidade total,8.1,NaN
3,AV005,2003-01-13,11:20:00,Aldrin + Dieldrin,NaN,NaN
4,AV005,2003-01-13,11:20:00,Alumínio dissolvido,NaN,NaN
5,AV005,2003-01-13,11:20:00,Alumínio total,NaN,NaN
6,AV005,2003-01-13,11:20:00,Arsênio Dissolvido,NaN,NaN
7,AV005,2003-01-13,11:20:00,Arsênio total,0.0015,NaN
8,AV005,2003-01-13,11:20:00,Atrazina,NaN,NaN
9,AV005,2003-01-13,11:20:00,Bário total,0.01,NaN

In [ ]:
# ============================================
# VALIDAÇÃO DA BASE LONG
# ============================================

print("Linhas esperadas:", len(df) * len(colunas_parametros))
print("Linhas obtidas:", len(df_long))

print("\nValores ausentes:")
print(df_long[["valor", "sinal"]].isna().sum())

print("\nNúmero de parâmetros:")
print(df_long["parametro"].nunique())

print("\nNúmero de estações:")
print(df_long["Estação"].nunique())

print("\nPeríodo:")
print(
    df_long["Data de Amostragem"].min(),
    "até",
    df_long["Data de Amostragem"].max()
)

Linhas esperadas: 3803040
Linhas obtidas: 3803040

Valores ausentes:
valor    2273689
sinal    3385131
dtype: int64

Número de parâmetros:
96

Número de estações:
769

Período:
1997-07-02 00:00:00 até 2019-12-12 00:00:00

In [127]:
# ============================================
# ANÁLISE 1 — COMPLETUDE POR PARÂMETRO
# ============================================

completude = (
    df_long
    .groupby("parametro")["valor"]
    .agg(
        total_observacoes="size",
        valores_preenchidos="count"
    )
    .reset_index()
)

completude["valores_ausentes"] = (
    completude["total_observacoes"]
    - completude["valores_preenchidos"]
)

completude["cobertura_%"] = (
    completude["valores_preenchidos"]
    / completude["total_observacoes"]
    * 100
)

# Ordena da menor para a maior cobertura
completude = completude.sort_values("cobertura_%")

display(completude)

print("Parâmetros com menor cobertura:")
display(completude.head(10))

print("\nParâmetros com maior cobertura:")
display(completude.tail(10))

,parametro,total_observacoes,valores_preenchidos,valores_ausentes,cobertura_%
72,Precipitação,39615,0,39615,0.000000
88,Transparência,39615,11,39604,0.027767
91,Vanádio total,39615,14,39601,0.035340
55,Manganês dissolvido,39615,28,39587,0.070680
49,Fluoreto ionizado,39615,88,39527,0.222138
68,Pentaclorofenol,39615,91,39524,0.229711
60,Molinato,39615,133,39482,0.335731
3,Aldrin + Dieldrin,39615,142,39473,0.358450
0,"2,4,6 Triclorofenol",39615,143,39472,0.360974
40,Endrin,39615,145,39470,0.366023
39,Endossulfan - alfa + beta,39615,146,39469,0.368547
58,Metoxicloro,39615,146,39469,0.368547
53,Lindano,39615,146,39469,0.368547
51,Heptacloro epóxido + Heptacloro,39615,146,39469,0.368547
8,Atrazina,39615,146,39469,0.368547
52,Hexaclorobenzeno,39615,146,39469,0.368547
89,Trifluoralina,39615,146,39469,0.368547
69,Permetrina - cis + trans,39615,146,39469,0.368547
76,Simazina,39615,146,39469,0.368547
31,DDT,39615,147,39468,0.371072
15,Clordano - cis + trans,39615,147,39468,0.371072
66,Ortofosfato,39615,161,39454,0.406412
73,Profundidade,39615,169,39446,0.426606
81,Sódio total,39615,178,39437,0.449325
71,Potássio total,39615,178,39437,0.449325
74,Saxitoxina,39615,545,39070,1.375742
59,Microcistina,39615,548,39067,1.383314
24,Condutividade elétrica laboratório,39615,584,39031,1.474189
35,Descarga Liquida,39615,883,38732,2.228954
43,Estanho total,39615,1064,38551,2.685851
84,Sólidos sedimentáveis,39615,1402,38213,3.539063
6,Arsênio Dissolvido,39615,1626,37989,4.104506
5,Alumínio total,39615,1774,37841,4.478102
48,Ferro total,39615,1917,37698,4.839076
9,Boro dissolvido,39615,3803,35812,9.599899
28,Cromo trivalente,39615,5221,34394,13.179351
26,Cromo hexavalente,39615,5544,34071,13.994699
10,Boro total,39615,6554,33061,16.544238
19,Cobre total,39615,6920,32695,17.468131
14,Cianeto total,39615,7959,31656,20.090875
41,Ensaio ecotoxicológico,39615,9273,30342,23.407800
34,Densidade de cianobactérias,39615,9702,29913,24.490723
75,Selênio total,39615,10850,28765,27.388615
94,pH laboratório,39615,11233,28382,28.355421
44,Estreptococos fecais,39615,13110,26505,33.093525
4,Alumínio dissolvido,39615,14390,25225,36.324625
13,Cianeto Livre,39615,16399,23216,41.395936
80,Sódio dissolvido,39615,16468,23147,41.570112
70,Potássio dissolvido,39615,16515,23100,41.688754
54,Magnésio total,39615,16879,22736,42.607598
11,Bário total,39615,17108,22507,43.185662
42,Escherichia coli,39615,17584,22031,44.387227
30,Cálcio total,39615,18075,21540,45.626657
95,Óleos e graxas,39615,18141,21474,45.793260
1,Alcalinidade de bicarbonato,39615,18270,21345,46.118894
78,Sulfato total,39615,18522,21093,46.755017
2,Alcalinidade total,39615,18750,20865,47.330557
37,Dureza de magnésio,39615,19005,20610,47.974252
36,Dureza de Cálcio,39615,19010,20605,47.986874
38,Dureza total,39615,19162,20453,48.370567
79,Sulfeto,39615,21271,18344,53.694308
20,Coliformes termotolerantes,39615,22022,17593,55.590054
57,Mercúrio total,39615,22858,16757,57.700366
7,Arsênio total,39615,23194,16421,58.548530
77,Substâncias tensoativas,39615,24228,15387,61.158652
65,Níquel total,39615,24641,14974,62.201186
27,Cromo total,39615,24921,14694,62.907989
18,Cobre dissolvido,39615,25849,13766,65.250536
64,Nitrogênio orgânico,39615,25988,13627,65.601414
46,Feoftina a,39615,26509,13106,66.916572
62,Nitrito,39615,26562,13053,67.050360
92,Zinco total,39615,27399,12216,69.163196
25,Cor verdadeira,39615,27709,11906,69.945728
29,Cádmio total,39615,28600,11015,72.194876
17,Clorofila a,39615,29380,10235,74.163827
12,Chumbo total,39615,30644,8971,77.354537
56,Manganês total,39615,30815,8800,77.786192
47,Ferro dissolvido,39615,31645,7970,79.881358
45,Fenóis totais,39615,32080,7535,80.979427
33,Demanda Química de Oxigênio,39615,33996,5619,85.815979
82,Sólidos dissolvidos totais,39615,34727,4888,87.661239
21,Coliformes totais,39615,36642,2973,92.495267
63,Nitrogênio amoniacal total,39615,38376,1239,96.872397
83,Sólidos em suspensão totais,39615,38726,889,97.755901
85,Sólidos totais,39615,38968,647,98.366780
61,Nitrato,39615,39276,339,99.144264
50,Fósforo total,39615,39288,327,99.174555
32,Demanda Bioquímica de Oxigênio,39615,39305,310,99.217468
87,Temperatura do ar,39615,39312,303,99.235138
22,Condição de tempo,39615,39330,285,99.280576
23,Condutividade elétrica in loco,39615,39461,154,99.611258
93,pH in loco,39615,39525,90,99.772813
16,Cloreto total,39615,39536,79,99.800581
90,Turbidez,39615,39556,59,99.851067
86,Temperatura da água,39615,39566,49,99.876309
67,Oxigênio dissolvido,39615,39567,48,99.878834

Parâmetros com menor cobertura:

,parametro,total_observacoes,valores_preenchidos,valores_ausentes,cobertura_%
72,Precipitação,39615,0,39615,0.000000
88,Transparência,39615,11,39604,0.027767
91,Vanádio total,39615,14,39601,0.035340
55,Manganês dissolvido,39615,28,39587,0.070680
49,Fluoreto ionizado,39615,88,39527,0.222138
68,Pentaclorofenol,39615,91,39524,0.229711
60,Molinato,39615,133,39482,0.335731
3,Aldrin + Dieldrin,39615,142,39473,0.358450
0,"2,4,6 Triclorofenol",39615,143,39472,0.360974
40,Endrin,39615,145,39470,0.366023

Parâmetros com maior cobertura:

,parametro,total_observacoes,valores_preenchidos,valores_ausentes,cobertura_%
50,Fósforo total,39615,39288,327,99.174555
32,Demanda Bioquímica de Oxigênio,39615,39305,310,99.217468
87,Temperatura do ar,39615,39312,303,99.235138
22,Condição de tempo,39615,39330,285,99.280576
23,Condutividade elétrica in loco,39615,39461,154,99.611258
93,pH in loco,39615,39525,90,99.772813
16,Cloreto total,39615,39536,79,99.800581
90,Turbidez,39615,39556,59,99.851067
86,Temperatura da água,39615,39566,49,99.876309
67,Oxigênio dissolvido,39615,39567,48,99.878834

In [128]:
# ============================================
# ANÁLISE 2 — COBERTURA AO LONGO DO TEMPO
# ============================================

parametros_principais = [
    "pH in loco",
    "Turbidez",
    "Oxigênio dissolvido",
    "Temperatura da água",
    "Condutividade elétrica in loco",
    "Demanda Bioquímica de Oxigênio",
    "Fósforo total",
    "Nitrato",
    "Sólidos totais",
    "Nitrogênio amoniacal total",
    "Coliformes termotolerantes"
]

df_long["ano"] = df_long["Data de Amostragem"].dt.year

cobertura_temporal = (
    df_long[df_long["parametro"].isin(parametros_principais)]
    .groupby(["ano", "parametro"])["valor"]
    .agg(
        total_observacoes="size",
        valores_preenchidos="count"
    )
    .reset_index()
)

cobertura_temporal["cobertura_%"] = (
    cobertura_temporal["valores_preenchidos"]
    / cobertura_temporal["total_observacoes"]
    * 100
)

display(cobertura_temporal.head(20))

print("Menores coberturas anuais:")

display(
    cobertura_temporal
    .sort_values("cobertura_%")
    .head(20)
)

,ano,parametro,total_observacoes,valores_preenchidos,cobertura_%
0,1997,Coliformes termotolerantes,421,421,100.000000
1,1997,Condutividade elétrica in loco,421,376,89.311164
2,1997,Demanda Bioquímica de Oxigênio,421,416,98.812352
3,1997,Fósforo total,421,404,95.961995
4,1997,Nitrato,421,418,99.287411
5,1997,Nitrogênio amoniacal total,421,421,100.000000
6,1997,Oxigênio dissolvido,421,421,100.000000
7,1997,Sólidos totais,421,321,76.247031
8,1997,Temperatura da água,421,421,100.000000
9,1997,Turbidez,421,421,100.000000
10,1997,pH in loco,421,421,100.000000
11,1998,Coliformes termotolerantes,745,739,99.194631
12,1998,Condutividade elétrica in loco,745,745,100.000000
13,1998,Demanda Bioquímica de Oxigênio,745,740,99.328859
14,1998,Fósforo total,745,745,100.000000
15,1998,Nitrato,745,745,100.000000
16,1998,Nitrogênio amoniacal total,745,745,100.000000
17,1998,Oxigênio dissolvido,745,745,100.000000
18,1998,Sólidos totais,745,745,100.000000
19,1998,Temperatura da água,745,745,100.000000

Menores coberturas anuais:

,ano,parametro,total_observacoes,valores_preenchidos,cobertura_%
242,2019,Coliformes termotolerantes,2786,0,0.000000
209,2016,Coliformes termotolerantes,2542,0,0.000000
198,2015,Coliformes termotolerantes,2626,0,0.000000
231,2018,Coliformes termotolerantes,2745,0,0.000000
220,2017,Coliformes termotolerantes,1734,0,0.000000
187,2014,Coliformes termotolerantes,2637,0,0.000000
176,2013,Coliformes termotolerantes,2586,614,23.743233
7,1997,Sólidos totais,421,321,76.247031
110,2007,Coliformes termotolerantes,1534,1298,84.615385
137,2009,Nitrogênio amoniacal total,2055,1819,88.515815
148,2010,Nitrogênio amoniacal total,2183,1940,88.868530
1,1997,Condutividade elétrica in loco,421,376,89.311164
159,2011,Nitrogênio amoniacal total,2309,2101,90.991771
126,2008,Nitrogênio amoniacal total,1841,1677,91.091798
115,2007,Nitrogênio amoniacal total,1534,1444,94.132986
103,2006,Nitrato,1322,1247,94.326778
88,2005,Coliformes termotolerantes,1156,1095,94.723183
117,2007,Sólidos totais,1534,1457,94.980443
71,2003,Nitrogênio amoniacal total,1159,1103,95.168248
69,2003,Fósforo total,1159,1103,95.168248

Achado: ausência total de valores de Coliformes termotolerantes entre 2014 e 2019 na base analisada.

Evidência: cobertura anual igual a 0% no período.

Interpretação: indica uma lacuna temporal relevante que deve ser investigada.

Limitação: a análise não permite determinar a causa da ausência.

In [129]:
# ============================================
# VALIDAÇÃO DOS ACHADOS
# ============================================

achados_validados = pd.DataFrame([
    {
        "id": "AV-01",
        "achado": "Baixa cobertura de alguns parâmetros",
        "evidencia": "Há parâmetros com cobertura muito baixa ou nula na base.",
        "interpretacao": "A disponibilidade dos parâmetros é heterogênea.",
        "conclusao_permitida": "A cobertura deve ser considerada antes de realizar análises específicas.",
        "conclusao_nao_permitida": "Concluir que os parâmetros com baixa cobertura são inválidos."
    },
    {
        "id": "AV-02",
        "achado": "Lacuna temporal de Coliformes termotolerantes",
        "evidencia": "A cobertura anual é 0% para Coliformes termotolerantes entre 2014 e 2019.",
        "interpretacao": "Existe uma lacuna temporal concentrada na disponibilidade desse parâmetro.",
        "conclusao_permitida": "O período deve ser sinalizado para investigação antes de análises que dependam desse parâmetro.",
        "conclusao_nao_permitida": "Afirmar a causa da ausência dos dados."
    },
    {
        "id": "AV-03",
        "achado": "Existência de valores extremos",
        "evidencia": "A auditoria identificou observações classificadas como candidatas a valores extremos pelo critério de IQR.",
        "interpretacao": "Algumas observações apresentam comportamento estatisticamente incomum.",
        "conclusao_permitida": "Os valores devem ser investigados no contexto da estação, período e parâmetro.",
        "conclusao_nao_permitida": "Classificar automaticamente um valor extremo como erro de medição."
    }
])

display(achados_validados)

,id,achado,evidencia,interpretacao,conclusao_permitida,conclusao_nao_permitida
0,AV-01,Baixa cobertura de alguns parâmetros,Há parâmetros com cobertura muito baixa ou nul...,A disponibilidade dos parâmetros é heterogênea.,A cobertura deve ser considerada antes de real...,Concluir que os parâmetros com baixa cobertura...
1,AV-02,Lacuna temporal de Coliformes termotolerantes,A cobertura anual é 0% para Coliformes termoto...,Existe uma lacuna temporal concentrada na disp...,O período deve ser sinalizado para investigaçã...,Afirmar a causa da ausência dos dados.
2,AV-03,Existência de valores extremos,A auditoria identificou observações classifica...,Algumas observações apresentam comportamento e...,Os valores devem ser investigados no contexto ...,Classificar automaticamente um valor extremo c...

In [130]:
# ============================================
# VALIDADOR DE ACHADOS
# ============================================

campos_obrigatorios = [
    "id",
    "achado",
    "evidencia",
    "interpretacao",
    "conclusao_permitida",
    "conclusao_nao_permitida"
]

validacao = []

for _, linha in achados_validados.iterrows():

    campos_preenchidos = all(
        pd.notna(linha[c]) and str(linha[c]).strip() != ""
        for c in campos_obrigatorios
    )

    validacao.append({
        "id": linha["id"],
        "status": "OK" if campos_preenchidos else "BLOQUEADO"
    })

resultado_validacao = pd.DataFrame(validacao)

display(resultado_validacao)

print(
    f"\nAchados validados: "
    f"{(resultado_validacao['status'] == 'OK').sum()}"
    f"/{len(resultado_validacao)}"
)

      id status
0  AV-01     OK
1  AV-02     OK
2  AV-03     OK

Achados validados: 3/3

In [131]:
# ============================================
# HARNESS / ORQUESTRAÇÃO
# ============================================
# Criar o controlador do sistema
# ============================================

def executar_pipeline():
    """
    Orquestra o fluxo de análise da qualidade da água.
    As operações analíticas são determinísticas;
    a interpretação por LLM pode ser adicionada posteriormente.
    """

    resultados = []

    # ----------------------------------------
    # ETAPA 1 — VERIFICAÇÃO DA ESTRUTURA
    # ----------------------------------------
    estrutura_ok = (
        len(pares_parametros) > 0
        and pares_parametros["sinal_existe"].all()
    )

    resultados.append({
        "etapa": "estrutura",
        "status": "OK" if estrutura_ok else "BLOQUEADO",
        "evidencia": (
            f"{len(pares_parametros)} parâmetros identificados; "
            f"{pares_parametros['sinal_existe'].sum()} com sinal correspondente."
        )
    })

    if not estrutura_ok:
        return pd.DataFrame(resultados)

    # ----------------------------------------
    # ETAPA 2 — QUALITY CHECKER
    # ----------------------------------------
    quality_ok = len(regras_qualidade) == 9

    resultados.append({
        "etapa": "quality_checker",
        "status": "OK" if quality_ok else "BLOQUEADO",
        "evidencia": f"{len(regras_qualidade)} regras de qualidade definidas."
    })

    if not quality_ok:
        return pd.DataFrame(resultados)

    # ----------------------------------------
    # ETAPA 3 — ANÁLISE
    # ----------------------------------------
    analise_ok = (
        len(completude) > 0
        and len(cobertura_temporal) > 0
    )

    resultados.append({
        "etapa": "analise",
        "status": "OK" if analise_ok else "BLOQUEADO",
        "evidencia": (
            f"{len(completude)} parâmetros avaliados quanto à completude; "
            f"{len(cobertura_temporal)} registros de cobertura temporal."
        )
    })

    if not analise_ok:
        return pd.DataFrame(resultados)

    # ----------------------------------------
    # ETAPA 4 — VALIDAÇÃO DOS ACHADOS
    # ----------------------------------------
    validacao_ok = (
        len(resultado_validacao) > 0
        and (resultado_validacao["status"] == "OK").all()
    )

    resultados.append({
        "etapa": "validacao_dos_achados",
        "status": "OK" if validacao_ok else "BLOQUEADO",
        "evidencia": (
            f"{(resultado_validacao['status'] == 'OK').sum()} "
            f"de {len(resultado_validacao)} achados validados."
        )
    })

    if not validacao_ok:
        return pd.DataFrame(resultados)

    # ----------------------------------------
    # ETAPA 5 — PRONTO PARA RELATÓRIO
    # ----------------------------------------
    resultados.append({
        "etapa": "relatorio",
        "status": "PRONTO",
        "evidencia": "Todas as etapas anteriores foram concluídas."
    })

    return pd.DataFrame(resultados)


pipeline = executar_pipeline()

display(pipeline)

,etapa,status,evidencia
0,estrutura,OK,96 parâmetros identificados; 96 com sinal corr...
1,quality_checker,OK,9 regras de qualidade definidas.
2,analise,OK,96 parâmetros avaliados quanto à completude; 2...
3,validacao_dos_achados,OK,3 de 3 achados validados.
4,relatorio,PRONTO,Todas as etapas anteriores foram concluídas.

In [132]:
# ============================================
# CRITÉRIO DE CONCLUSÃO DO PIPELINE
# ============================================

pipeline_concluido = (
    (pipeline["status"].isin(["OK", "PRONTO"])).all()
    and pipeline.iloc[-1]["status"] == "PRONTO"
)

print(
    "PIPELINE CONCLUÍDO"
    if pipeline_concluido
    else "PIPELINE NÃO CONCLUÍDO"
)

PIPELINE CONCLUÍDO

In [133]:
# ============================================
# RELATÓRIO FINAL
# ============================================

relatorio_final = f"""
# Relatório de Análise Exploratória e Controle de Qualidade
## Monitoramento da Qualidade das Águas em Minas Gerais

### 1. Objetivo

Este relatório apresenta os resultados produzidos pelo sistema desenvolvido
para análise exploratória e controle de qualidade de dados de monitoramento
da qualidade das águas.

O sistema combina verificações determinísticas realizadas por código,
análise exploratória e validação dos achados antes da elaboração das
conclusões.

---

### 2. Base analisada

A demonstração foi realizada a partir da base histórica do Programa
Águas de Minas, do IGAM, utilizando a planilha "SH ATÉ DEZ 2019".

Características da base:

- Registros de amostragem: {len(df):,}
- Estações: {df["Estação"].nunique()}
- Parâmetros disponíveis: {len(colunas_parametros)}
- Período: {df["Data de Amostragem"].min().strftime("%d/%m/%Y")}
  a {df["Data de Amostragem"].max().strftime("%d/%m/%Y")}

Para a análise exploratória detalhada foram utilizados
{len(parametros_principais)} parâmetros principais.

---

### 3. Controle de qualidade

Foram executadas {len(regras_qualidade)} regras de qualidade,
abrangendo aspectos de:

- estrutura;
- completude;
- completude temporal;
- consistência;
- valores extremos;
- cobertura amostral;
- semântica;
- dados ausentes.

A estrutura principal apresentou {len(pares_parametros)} parâmetros
com suas respectivas colunas de sinal.

Não foram identificadas duplicidades pela chave
Estação + Data de Amostragem + Hora de Amostragem.

Os valores ausentes foram preservados durante o processo de
padronização dos dados.

---

### 4. Padronização dos dados

A estrutura original, em formato wide, foi transformada para o formato
long, resultando em {len(df_long):,} registros analíticos.

A transformação preservou:

- estação;
- data e hora da amostragem;
- parâmetro;
- valor observado;
- sinal associado à observação;
- valores ausentes.

Essa estrutura permite realizar análises por parâmetro, estação e período
de maneira padronizada.

---

### 5. Principais achados

#### 5.1 Cobertura dos parâmetros

A disponibilidade dos parâmetros é heterogênea.

Na base analisada, alguns parâmetros apresentam cobertura muito baixa,
enquanto parâmetros como Oxigênio dissolvido, Temperatura da água e
Turbidez apresentam cobertura superior a 99%.

Essa diferença deve ser considerada antes da realização de análises
específicas.

Baixa cobertura não é interpretada automaticamente como erro ou
invalidação do parâmetro.

#### 5.2 Lacuna temporal

Foi identificada ausência total de valores de Coliformes termotolerantes
entre 2014 e 2019 na base analisada.

A cobertura anual do parâmetro é igual a 0% nesse período.

O resultado indica uma lacuna temporal relevante na disponibilidade
do parâmetro.

A análise realizada não permite determinar a causa dessa ausência.

#### 5.3 Valores extremos

A auditoria identificou observações classificadas como candidatas a
valores extremos pelo critério de intervalo interquartil (IQR).

Essas observações são tratadas como pontos que merecem investigação
contextual, considerando estação, período e parâmetro.

Um valor extremo não é automaticamente classificado como erro de
medição.

---

### 6. Validação dos achados

Foram avaliados {len(achados_validados)} achados estruturados.

Cada achado foi associado a:

- evidência observável;
- interpretação;
- conclusão permitida;
- conclusão que deve ser evitada.

Esse mecanismo busca impedir que uma observação estatística seja
transformada automaticamente em uma afirmação causal ou em um
diagnóstico ambiental.

---

### 7. Limitações

Os resultados devem ser interpretados considerando o escopo da base
e as limitações do processo.

O sistema não permite:

- estabelecer causalidade;
- determinar a causa de dados ausentes;
- classificar automaticamente valores extremos como erros;
- produzir diagnóstico ambiental definitivo;
- inferir riscos à saúde;
- afirmar conformidade regulatória;
- substituir avaliação técnica especializada.

---

### 8. Critério de conclusão

O pipeline considera a análise concluída somente após a execução das
etapas de:

**estrutura → controle de qualidade → análise → validação dos achados.**

Status final do pipeline: **{pipeline.iloc[-1]["status"]}**

A execução foi considerada concluída porque as etapas previstas
retornaram os critérios de aceite definidos pelo sistema.
"""

print(relatorio_final)

# Relatório de Análise Exploratória e Controle de Qualidade
## Monitoramento da Qualidade das Águas em Minas Gerais

### 1. Objetivo

Este relatório apresenta os resultados produzidos pelo sistema desenvolvido
para análise exploratória e controle de qualidade de dados de monitoramento
da qualidade das águas.

O sistema combina verificações determinísticas realizadas por código,
análise exploratória e validação dos achados antes da elaboração das
conclusões.

---

### 2. Base analisada

A demonstração foi realizada a partir da base histórica do Programa
Águas de Minas, do IGAM, utilizando a planilha "SH ATÉ DEZ 2019".

Características da base:

- Registros de amostragem: 39,615
- Estações: 769
- Parâmetros disponíveis: 96
- Período: 02/07/1997
  a 12/12/2019

Para a análise exploratória detalhada foram utilizados
11 parâmetros principais.

---

### 3. Controle de qualidade

Foram executadas 9 regras de qualidade,
abrangendo aspectos de:

- estrutura;
- completude;
- completude temporal;
- consistência;
- valores extremos;
- cobertura amostral;
- semântica;
- dados ausentes.

A estrutura principal apresentou 96 parâmetros
com suas respectivas colunas de sinal.

Não foram identificadas duplicidades pela chave
Estação + Data de Amostragem + Hora de Amostragem.

Os valores ausentes foram preservados durante o processo de
padronização dos dados.

---

### 4. Padronização dos dados

A estrutura original, em formato wide, foi transformada para o formato
long, resultando em 3,803,040 registros analíticos.

A transformação preservou:

- estação;
- data e hora da amostragem;
- parâmetro;
- valor observado;
- sinal associado à observação;
- valores ausentes.

Essa estrutura permite realizar análises por parâmetro, estação e período
de maneira padronizada.

---

### 5. Principais achados

#### 5.1 Cobertura dos parâmetros

A disponibilidade dos parâmetros é heterogênea.

Na base analisada, alguns parâmetros apresentam cobertura muito baixa,
enquanto parâmetros como Oxigênio dissolvido, Temperatura da água e
Turbidez apresentam cobertura superior a 99%.

Essa diferença deve ser considerada antes da realização de análises
específicas.

Baixa cobertura não é interpretada automaticamente como erro ou
invalidação do parâmetro.

#### 5.2 Lacuna temporal

Foi identificada ausência total de valores de Coliformes termotolerantes
entre 2014 e 2019 na base analisada.

A cobertura anual do parâmetro é igual a 0% nesse período.

O resultado indica uma lacuna temporal relevante na disponibilidade
do parâmetro.

A análise realizada não permite determinar a causa dessa ausência.

#### 5.3 Valores extremos

A auditoria identificou observações classificadas como candidatas a
valores extremos pelo critério de intervalo interquartil (IQR).

Essas observações são tratadas como pontos que merecem investigação
contextual, considerando estação, período e parâmetro.

Um valor extremo não é automaticamente classificado como erro de
medição.

---

### 6. Validação dos achados

Foram avaliados 3 achados estruturados.

Cada achado foi associado a:

- evidência observável;
- interpretação;
- conclusão permitida;
- conclusão que deve ser evitada.

Esse mecanismo busca impedir que uma observação estatística seja
transformada automaticamente em uma afirmação causal ou em um
diagnóstico ambiental.

---

### 7. Limitações

Os resultados devem ser interpretados considerando o escopo da base
e as limitações do processo.

O sistema não permite:

- estabelecer causalidade;
- determinar a causa de dados ausentes;
- classificar automaticamente valores extremos como erros;
- produzir diagnóstico ambiental definitivo;
- inferir riscos à saúde;
- afirmar conformidade regulatória;
- substituir avaliação técnica especializada.

---

### 8. Critério de conclusão

O pipeline considera a análise concluída somente após a execução das
etapas de:

**estrutura → controle de qualidade → análise → validação dos achados.**

Status final do pipeline: **PRONTO**

A execução foi considerada concluída porque as etapas previstas
retornaram os critérios de aceite definidos pelo sistema.

In [134]:
# Salvar relatório final em Markdown

with open("relatorio_final.md", "w", encoding="utf-8") as arquivo:
    arquivo.write(relatorio_final)

print("Relatório salvo como: relatorio_final.md")

Relatório salvo como: relatorio_final.md